/* -- SimpleSal: ssTEA, ssUI, and ssIO | (C) 2025, 2026 TruSoft Computing LLC |  All rights reserved. --
   This software is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
   This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
   ---------------------------------------------------------------------------------------------------
 *
 * app-events.ino       Arduino main program demonstrating Time and Data Events based on ssTEA.
 *
 **************************************************************************************************/
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// This is a SimpleSal App developed and published by TSC LLC to demonstrate SimpleSal App features.
// -------------------------------------------------------------------------------------------------
// This App demonstrates the level of complexity SimpleSal supports: more than loop, less than RTOS.
// SimpleSal's Time and Event API helps solve complex problems a looping baremetal algorithm can't.
// The solutions are simplified versions of RTOS or OS algorithms: Time- and Event-based software.
// -------------------------------------------------------------------------------------------------
// This minimum App demonstrates software in a legacy App interacting with ssTEA and ssUI real-time.
// The App's (forced) design: App's loop emits signals causing ssTEA to grant the Time Event Agency.
// The legacy code turns the BuiltIn LED On every second, ignoring the state it is in at the time.
// The demonstration of ssTEA includes a Time Event to turn the LED Off at some later point in Time,
// and a Data Event to display data generated by the Time Event.  The key word is demonstration.
// -------------------------------------------------------------------------------------------------
// The order or sequence of these statements within the source file at some level has to be retained
// because the processor of the language builds knowledge of the software incrementally as it goes.
// -------------------------------------------------------------------------------------------------
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// SimpleSal has a software philosphy: everything that happens in life does NOT involve magic. All
// of the hallenges to portability have technical solutions in the build environment and software.
// -------------------------------------------------------------------------------------------------
// Software portability across build environments (compilers, memory maps, allocations) may be
// managed at the very highest level by separating Arduino, Linux, Windows, RTOS, barebones, etc.
// -------------------------------------------------------------------------------------------------
#define     HOST_ONEOF_hostOS_Is_Arduino

// -------------------------------------------------------------------------------------------------
// Each platform has a variety of memory types, control over what goes where is often in the C code.
// For example: removing "static" from the ReadOnly #define might move strings from Flash to RAM.
// (note: The strings arrive in Flash with the binary image; a copy is accessed by code in RAM.)
// -------------------------------------------------------------------------------------------------
#define     ReadOnly    static

// -------------------------------------------------------------------------------------------------
// Software portability across Time from the same human brain requires some words remain constant.
// A HOST build environment that defines boolean and Null can be quite cranky about a re-define.
// -------------------------------------------------------------------------------------------------
#define     HOST_ONEOF_ssHL_defines_boolean
#define     HOST_ONEOF_ssHL_defines_Null

// -------------------------------------------------------------------------------------------------
// The definition of the simplest configuration depends on the file the build tool finds and uses.
// -------------------------------------------------------------------------------------------------
// This SimpleSal App is meant to build with "ss_configuration.start" with extension changed to ".h".
// -------------------------------------------------------------------------------------------------
#define     SS_OPTIN_INCLUDE_SSTEA
#define     SS_ACCEPT_SIMPLEST_CONFIG

#include "ss_configuration.h"

// -------------------------------------------------------------------------------------------------
// Software portability across platforms requires operational levers built in that hide differences.
// The levers are defined in "mesa_min_dcl" and "mesa_min_def"; ssTEA uses micros() and Ascii.
// -------------------------------------------------------------------------------------------------
// This SimpleSal App is meant to build with "mesa_min_dcl.start" with extension changed to ".h".
// -------------------------------------------------------------------------------------------------
#include "mesa_min_dcl.h"

// -------------------------------------------------------------------------------------------------
// Using ssTEA data types, App data types for Events may be declared HERE.  ssTEA Event maintains
// data About the Event; ssTea refers to the App's data type when the Event is granted Agency.
// -------------------------------------------------------------------------------------------------
// This is one of the "moderately complex" software concepts required to write signaling software:
//   there are many kinds of signal/sensor devices and any number of each in a single application.
// The data structures used as an organizing concept "about" any object are signal carriers; the
// organization of the signal carriers and the relationship they support influences the algorithm.
// -------------------------------------------------------------------------------------------------
#include "SimpleSal\ssTEA\ssTEA_data_dcl.h"

#define     TIME_EVENT_EVAPI    (0)         //  the simplest config allocates 2 EvApis for the App
#define     DATA_EVENT_EVAPI    (1)

#define     APP_DATA_ALLOC      (40)
#define     APP_DATA_MAX_I      (APP_DATA_ALLOC-1)

typedef struct App_EventDataDesc_s
{
    boolean             TimeToPause;
    boolean             TimeToStop;
    AsciiA_t            Data[APP_DATA_ALLOC];
}   App_EventDataDesc_t,  *App_pEventDataDesc_t;

typedef App_EventDataDesc_t      App_EventData_t;       // referenced by ssTEA data type directly
typedef App_pEventDataDesc_t     App_pEventData_t;
#define App_pEventDataNull       ((App_pEventData_t) NULL)

#include "SimpleSal\ss_include_dcl.h"

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// The included file has helpers for Apps interacting with ssTEA through ssTEA's software interface.
// The function declarations are the App's functions making use of the API to interation with ssTEA.
// They represent the three phases of life of an FSM within ssTEA: definition, launch, operation.
// -------------------------------------------------------------------------------------------------
#include "api_ssTEA_dcl.h"

// -------------------------------------------------------------------------------------------------
// The App's ssTEA functionality is defined AFTER ssTEA knowledge is included; this function hides
// that dependency from the App loop. As originally written, the App loop only knows about the mesa.
// -------------------------------------------------------------------------------------------------
void    AppLoop_ssTEA_Interface (void);

ssE_EvResult_t  App_EventLauncher (void);

ssE_EvResult_t  App_TimeEvent_Define     (ssUI_db_pEvApi_t    pEvApi);
ssE_EvResult_t  App_TimeEvent_Launch     (ssUI_db_pEvApi_t    pEvApi);
ssE_EvResult_t  App_TimeEvent_Operate    (ssE_pAboutEvVoid_t  param1, ssT_pTime_t pCurrentTime);

ssE_EvResult_t  App_DataEvent_Define     (ssUI_db_pEvApi_t    pEvApi);
ssE_EvResult_t  App_DataEvent_Launch     (ssUI_db_pEvApi_t    pEvApi);
ssE_EvResult_t  App_DataEvent_Operate    (ssE_pAboutEvVoid_t  param1, ssT_pTime_t pCurrentTime);

// -------------------------------------------------------------------------------------------------
// An alternative allocation of ssTEA variables, as supported by ssTEA, is to use ssUI's free ones.
// ssTEA also provides a variety of constant Time definitions of useful periods of Time for the App.
// -------------------------------------------------------------------------------------------------
#define App_Cycle_FullCyclePeriod       ssT_gpTime_5sc
#define App_Cycle_DutyCyclePeriod       ssT_gpTime_3sc

#define App_default_StartTimeFromNow    ssT_gpTime_10sc

// -------------------------------------------------------------------------------------------------
// The UI shared between the App and ssUI is simplified here by ssUI sending "app ..." input here.
// -------------------------------------------------------------------------------------------------
void        App_HeyProcessThis (pAsciiA_t  pReceivedInput);

// -------------------------------------------------------------------------------------------------
// This SimpleSal App is meant to build with "mesa_min_def.start" with extension changed to ".h".
// -------------------------------------------------------------------------------------------------
#include "mesa_min_def.h"

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// Because ssUI co-exists with the App, it needs to begin existence with Resources correlated to App
// -------------------------------------------------------------------------------------------------
#define  ssUI_Default_LED_RO_state          mesa_RO_state_App
#define  ssUI_Default_LED_RO_substate       mesa_RO_substate_none
#define  ssUI_Default_Ascii_RO_state        mesa_RO_state_App
#define  ssUI_Default_Ascii_RO_substate     mesa_RO_substate_none
#define  ssUI_Default_Matrix_RO_state       mesa_RO_state_App
#define  ssUI_Default_Matrix_RO_substate    mesa_RO_substate_none

#define  ssUI_Default_Verbosity             true

// -------------------------------------------------------------------------------------------------
// Allocations of data and definition of functions with parameters, as declared by ss_include_dcl.h
// -------------------------------------------------------------------------------------------------
#include "SimpleSal\ss_include_def.h"

// -------------------------------------------------------------------------------------------------
// The interfaces to the mesa, ssTEA and ssUI are now fully referenceable by App software.
// -------------------------------------------------------------------------------------------------

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// This is just a compilation trick of ssHL C or C++ that hides whether the software exists or not.
// All of the references in the software remain the same whether selecting announce activity or not.
// When the compiler finds the reference, and the selection is "not announce", nothing is compiled.
// -------------------------------------------------------------------------------------------------
// #define APP_OPTIN_ANNOUNCE_SSTEA
#define APP_OPTIN_ANNOUNCE_EVENT
#define APP_OPTIN_ANNOUNCE_APP

#ifdef APP_OPTIN_ANNOUNCE_SSTEA
#define App_Announce_ssTEA(xpThis)  { mesa_uiOp_emit_qAsciiA (xpThis); mesa_uiOp_emit_newline (); }
#else  // not APP_OPTIN_ANNOUNCE_SSTEA
#define App_Announce_ssTEA(xthis)
#endif // APP_OPTIN_ANNOUNCE_SSTEA

#ifdef APP_OPTIN_ANNOUNCE_EVENT
#define App_Announce_Event(xpThis)  { mesa_uiOp_emit_qAsciiA (xpThis); mesa_uiOp_emit_newline (); }
#else  // not APP_OPTIN_ANNOUNCE_EVENT
#define App_Announce_Event(xpThis)
#endif // APP_OPTIN_ANNOUNCE_EVENT

#ifdef APP_OPTIN_ANNOUNCE_APP
#define App_Announce_App(xpThis)    { mesa_uiOp_emit_qAsciiA (xpThis); mesa_uiOp_emit_newline (); }
#else  // not APP_OPTIN_ANNOUNCE_APP
#define App_Announce_App(xthis)
#endif // APP_OPTIN_ANNOUNCE_APP

// -------------------------------------------------------------------------------------------------
// This SimpleSal App either builds into a display, as Time occurs, of a counting-up Clock; or,
// of a counting-up Timer.  The output must correlate to the display device: An Arduino IDE Serial
// display user will see the time displayed in a long line off the screen; clearing the buffer
// rapidly will show Time occurring.  Other terminal programs are more configurable.  A display of
// the Time on a new line each time in this App shows how often the App loop function is running.
// Higher baud rates increase the ability to display and so the App loop gets to run more often.
// The value of displaying a Clock versus a Timer is based on the human's comparison to true Time.
// -------------------------------------------------------------------------------------------------
#define APP_ONEOF_CLOCK_OR_TIMER_IS_TIMER
// #define APP_ONEOF_CLOCK_OR_TIMER_IS_CLOCK

#ifdef APP_ONEOF_CLOCK_OR_TIMER_IS_TIMER
ReadOnly    pAsciiA_t   pcMsg_InitBanner    = S("Timer App Events initializing ssTEA...");
ReadOnly    pAsciiA_t   pcMsg_AppCoexists   = S("Timer App co-existing with ssTEA...");
#endif  // APP_ONEOF_CLOCK_OR_TIMER_IS_TIMER

#ifdef APP_ONEOF_CLOCK_OR_TIMER_IS_CLOCK
ReadOnly    pAsciiA_t   pcMsg_InitBanner    = S("Clock App Events initializing ssTEA...");
ReadOnly    pAsciiA_t   pcMsg_AppCoexists   = S("Clock App co-existing with ssTEA...");
#endif  // APP_ONEOF_CLOCK_OR_TIMER_IS_CLOCK


pAsciiA_t   pcMsg_AppInit = S("<mesa [P39] and App [events] init...app-events>");

// -------------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------------
#define     App_Default_Agency_pace         ssTEA_Agency_pace_period
#define     App_Default_Agency_pace_period  ssTEA_Agency_pace_period_minimum

#define APP_BUFFER_ALLOC  100
#define APP_BUFFER_MAX_I  (APP_BUFFER_ALLOC-1)

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// The function is owned by the App and specific to the App.  Dependencies are resolved here.
// For example, configure events and start Time and Agency in support of the App's use of ssTEA.
// The starting position is determined by values is ssTEA_control, as set by App during setup.
// This is the software that will be added to an arduino project to incorporate ssTEA and ssUI.
// -------------------------------------------------------------------------------------------------
void App_ss_launch (void)
{
    AsciiA_t    localBuff[APP_BUFFER_ALLOC];

    ssTEA_control.Time_state = ssTEA_state_stopped;
    ssTEA_control.Time_base = ssTEA_Time_base_reality;
    ssTEA_control.Agency_state = ssTEA_state_stopped;
    ssTEA_control.Agency_pace = App_Default_Agency_pace;
    ssTEA_control.Agency_period = App_Default_Agency_pace_period;

    ssTEA_control.Show_Path = false;
    ssTEA_control.Show_Cause = true;
    ssTEA_control.Show_Signals = true;
    ssTEA_control.Show_Notes = true;

    // if a hard fault occurs in ssTEA, the serial output may not get a chance, can wait for done
    mesa_uiOp_emit_qAsciiA ("<ssTEA init...");
    ssTEA_InitState ();
    mesa_uiOp_emit_qAsciiA ("success>");
    mesa_uiOp_emit_newline ();

    mesa_uiOp_emit_qAsciiA ("<ssUI init...");
    ssUI_InitState ();
    mesa_uiOp_emit_qAsciiA ((ssUI_control.BeVerbose) ? "{verbose, even loquacious}" : "{quiet}");
    mesa_uiOp_emit_qAsciiA ("success>");
    mesa_uiOp_emit_newline ();

//  App_BuildOp_Show_Build ();

    // ---------------------------------------------------------------------------------------------
    // The App is now up and running, ssTEA is configured and running as configured: "hello, world".
    // This App chooses to set the Current Time to the Time the software was built
    // ---------------------------------------------------------------------------------------------
    if (ssT_stampOp_TimeOfBuild_AsciiToTime (localBuff))
    {
        ssT_mathOp_P1getsP2 (ssT_gpTime_Current, ssT_gpTime_Built);
        mesa_uiOp_emit_qAsciiA ("Timc built:");
        ss_uiOp_Show_Time (ssT_gpTime_Built, lfY);
    }

    mesa_uiOp_emit_qAsciiA ("App events  ");
    App_EventLauncher ();

} // App_ss_launch
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// The included file has helpers for Apps interacting with ssTEA through ssTEA's software interface.
// The function definitions are the App's functions making use of the API to interation with ssTEA.
// They represent the three phases of life of an FSM within ssTEA: definition, launch, operation.
// -------------------------------------------------------------------------------------------------
#include "api_ssTEA_def.h"

// =================================================================================================
#undef  setup

#define setup   App_setup

void setup (void)       // the App's original setup function, ssTEA calls as App_setup.
{
    // this content was in the App's original setup function, copied here before adding SimpleSal
    /* original App */

    // this content added to the App's original setup function, co-existence has a price.
    mesa_Ascii_RO_state     = mesa_RO_state_App;
    mesa_Ascii_RO_substate  = mesa_RO_substate_none;

    mesa_uiOp_deviceInitialize ();

    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_qAsciiA ("original App setup complete...");
    mesa_uiOp_emit_newline ();

    mesa_gCtOf_1usThis1ms  = 0;
    mesa_gCtOf_1msThis100ms = 0;
    mesa_gCtOf_1msThisCycle = 0;
    mesa_gCtOf_1msFreeRunning = 0;

}   // setup            // the App's original setup function

#undef setup            // don't forget to forget #define

// the ssHL compiler has seen and compiled "App_setup", and has not yet seen anything called "setup".

// =================================================================================================
#undef  loop

#define loop    App_loop

int iterations = 1;     // debug tool to stop display because IDE is limited

void loop (void)        // (the App's original loop function, ssTEA calls as App_loop)
{
    // ---------------------------------------------------------------------------------------------
    // This is a "legacy" Arduino loop function: watching a microsecond counter change over Time.
    // Within Arduino, the function "micros ()" returns the number of microseconds since Time began.
    // This makes it possible to see how many microseconds occured since we last checked the Time.
    // The number of micros from one loop to the next, "loop1 to loop2", is calculated by ssTEA.
    // ---------------------------------------------------------------------------------------------
    mesa_gCtOf_1usThis1ms += ssT_us_gLoop1toLoop2;

    // ---------------------------------------------------------------------------------------------
    // This causes the user's loop function (below) to only execute one time each 1000 microseconds.
    // ---------------------------------------------------------------------------------------------
    if (mesa_gCtOf_1usThis1ms <= SST_USECS_PER_MSEC)
    {
        return;
    }
    mesa_gCtOf_1usThis1ms = 0;

    // ---------------------------------------------------------------------------------------------
    // FreeRunning is a 32-bit number.  That number "modulo 1000" creates a remainder.  When the
    // remainder is zero, 1000 milliseconds have passed, or, 1 second.  Math is inherent in the
    // ability of the processor, math is what is was designed to do; the instructions are optimal.
    // The method does requires the compiler store 32-bit values (1,000 and 20,000) somewhere nearby.
    // ---------------------------------------------------------------------------------------------
    mesa_gCtOf_1msFreeRunning++;
    if ((mesa_gCtOf_1msFreeRunning % SST_MSECS_PER_SEC) == 0)       // make the serial LED blink
    {
        if (iterations > 0)
        {
            mesa_uiOp_emit_1 (Ascii_ESC);
            if ((mesa_gCtOf_1msFreeRunning % (SST_MSECS_PER_SEC * 20)) == 0)
            {
                mesa_uiOp_emit_newline ();                              // move the display
                iterations--;
            }
        }   //
    }   // the App signal of activity while in loop is the serial port 1 value each 1 second

    if (iterations > 0)
    {
        // ---------------------------------------------------------------------------------------------
        // The count of millis this Cycle is not Free Running; but in fact the value of the Count is the
        // same value as the remainder that would have been computed based on the Free Running Count.
        // The valid range of values is constrained to the Cycle's millisecond range as decided by the App.
        // Finally, this solution considers any number over a maximum rather than specific maximum values.
        // ---------------------------------------------------------------------------------------------
        mesa_gCtOf_1msThisCycle++;
        if (mesa_gCtOf_1msThisCycle >= 5000)         // 5 1000-millisecond seconds use 5000 milliseconds
        {
            mesa_gCtOf_1msThisCycle = 0;

            // ssTEA and the App co-exist, so the deeply internal Agency state of ssTEA is easily seen.
            // if ssTEA Time and Agency FSMs are not operating, this App does not attempt to use them.
            if (ssTEA_control.Agency_state == ssTEA_state_running)
            {
                // the "events App": using a legacy timekeeping method, assert LED On each second.
                mesa_uiOp_LEDon ();

                // Schedule a Time Event in the App to turn the LED Off after a period of Time.
                AppLoop_ssTEA_Interface ();
            }   // ssTEA Agency running means ssTEA Time is running
        }   // timeout occured
    }   // debug tool to stop display because IDE is limited
    // 1 millisecond of Time has gone by since we were last here in the algorithm

    // ---------------------------------------------------------------------------------------------
    // Similar to count the number of milliseconds for the Full Cycle, the ssUI menus run only on
    // a periodic basis that is appropriate for the human UI: 100 millisecond delays not noticable.
    // ---------------------------------------------------------------------------------------------
    mesa_gCtOf_1msThis100ms += 1;
    if (mesa_gCtOf_1msThis100ms >= 100)          // ssTEA does not inherently manage 100ms units
    {
        mesa_gCtOf_1msThis100ms = 0;

        // ---------------------------------------------------------------------------------------------
        // At the period of 100ms, the UI state machine or FSM of ssTEA runs; App input is forwarded
        // to the "App_HeyProcessThis (pAscii_t);" function that the user implements or leaves empty.
        // ---------------------------------------------------------------------------------------------
        if (mesa_Ascii_RO_state == mesa_RO_state_SimpleSal)
        {
            ssUI_Main ();
        }
    }   // 100ms period occured
}   // loop             // the App's original loop function, known as "App_loop"

#undef  loop            // don't forget to forget #define

// the ssHL compiler has seen and compiled "App_loop", and has not yet seen anything called "loop".
// =================================================================================================
#undef ssTEA_setup

#define ssTEA_setup  setup



void ssTEA_setup (void) // the one called by Arduino Host OS Api using the name "setup"
{
    AsciiA_t    localBuff[APP_BUFFER_ALLOC];

    // ---------------------------------------------------------------------------------------------
    // Call the original App's "setup", which was renamed to "App_setup" when the compiler found it.
    // This is software written without ssTEA so it may continue to execute before ssTEA is launched.
    // ---------------------------------------------------------------------------------------------
    App_setup ();

    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();

    ss_uiOp_pBanner (lfN, pcMsg_InitBanner, lfY);

    if (ssT_stampOp_TimeOfBuild_AsciiToTime (localBuff))
    {
        mesa_uiOp_emit_qAsciiA ("Time built:");
        ss_uiOp_Show_Time (ssT_gpTime_Built, lfY);
    }   // successfully translated a string's contents into a Time variable's contents

    App_ss_launch ();

    ss_uiOp_pBanner (lfN, pcMsg_AppCoexists, lfY);

    ssTEA_control.Time_state = ssTEA_state_running;
    ssTEA_control.Agency_state = ssTEA_state_running;

    ss_uiOp_Show_ssTime_state ();
    ss_uiOp_Show_ssAgency_state ();

    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();

} // ssTEA_setup        // the one called by Arduino Host OS Api using the name "setup"

#undef ssTEA_setup      // don't forget to forget #define

// the ssHL compiler has seen and compiled "App_setup" and "setup"

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// "App_loop" is the original Arduino App's "loop" function, which will now be granted agency
// by ssTEA's "loop".  This was done by a #define trick in this file: rename the original App "loop"
// to "App_loop" and rename "ssTEA_loop" to "loop".  The result is the linker sees two functions:
// "App_loop" and "loop".  Instructions may be found elsewhere describing how to modify Original App.
// -------------------------------------------------------------------------------------------------
// This function should be usable as-is and used as-is.  This is where Time is perceived by ssTEA.
// When Agency granted by the Host OS has been intercepted here, Agency is granted first to ssTEA
// to manage Events, and finally Agency is granted to the App to react to the Events that occured.
// -------------------------------------------------------------------------------------------------
// ssTEA computes the consumption of Time by App Events inside ssTEA and by the App outside ssTEA.
// Because ssTEA bases all knowledge of Time on us_gLoop1toLoop2, software here that lies about the
// number of microseconds could basically make the entire ssTEA-based application into a Time-based
// simulation of the environment the algorithm interacts with.  Or something along those lines.
// -------------------------------------------------------------------------------------------------
#undef loop

#define ssTEA_loop loop

void ssTEA_loop (void)
{
    ssTEA_Time_MathEntry ();

    ssTEA_Agency_Root (ssT_us_gLoop1toLoop2, ssT_ms_gLoop1toLoop2);

    ssTEA_Time_MathExit ();

    App_loop ();

} // ssTEA_loop

#undef ssTEA_loop       // don't forget to forget #define

// the ssHL compiler has seen and compiled "App_loop" and "loop"
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------------
void    AppLoop_ssTEA_Interface (void)
{
    ssUI_db_pEvApi_t    pEvApi;

#ifdef APP_OPTIN_ANNOUNCE_EVENT
    App_Announce_Event ("------" );
    App_Announce_Event ("User loop turned LED On at N*1 second Time boundary.");
    ss_uiOp_Show_Time (ssT_gpTime_Current, lfY);
#endif  // APP_OPTIN_ANNOUNCE_EVENT

    // ---------------------------------------------------------------------------------------------
    // What the "app-events.ino" does: WHEN the LED is turned On (here), a Time period starts
    // during which the LED will be On.  When that period ends, the LED will be turned off.
    // The Time at which the Event is based on software setting OccursAt to "Current + period"
    // AND signaling the Time Event to resume; this causes the Time Event to participate.
    // When the Time Event is granted Agency, it will set the LED to Off and then pause again.
    // ---------------------------------------------------------------------------------------------
    // When the ssUI variable ssUI_gpTimeA has a value of zero, Time Event occurs immediately.
    // When the variable is non-zero, the Time Event occurs at the end of a Duty Cycle Period.
    // ---------------------------------------------------------------------------------------------
    pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (TIME_EVENT_EVAPI);
    ssUI_dbOp_Show_OneEvApi (pEvApi);
    ssT_mathOp_P1getsP2 (&pEvApi->pssTEA_ApiSig->ssE_pAboutEv->OccursAt, ssT_gpTime_Current);
#ifdef APP_OPTIN_ANNOUNCE_EVENT
    ss_uiOp_Show_Time (&pEvApi->pssTEA_ApiSig->ssE_pAboutEv->OccursAt, lfY);
#endif  // APP_OPTIN_ANNOUNCE_EVENT
    ssT_mathOp_P1getsP1plusP2 (&pEvApi->pssTEA_ApiSig->ssE_pAboutEv->OccursAt,
                                App_Cycle_DutyCyclePeriod);
#ifdef APP_OPTIN_ANNOUNCE_EVENT
    App_Announce_Event ("Off scheduled @");
    ss_uiOp_Show_Time (&pEvApi->pssTEA_ApiSig->ssE_pAboutEv->OccursAt, lfY);
#endif  // APP_OPTIN_ANNOUNCE_EVENT

    switch (pEvApi->pssTEA_ApiSig->ssE_pAboutEv->Runfsm_state)
    {
        case ssA_Runfsm_State_stopped   :
            App_Announce_Event ("Stopped Time Event, an error.");
            break;
        case ssA_Runfsm_State_paused    :
            if (!ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgRunfsm_Resume))
            {
                App_Announce_Event ("Paused Time Event did not Resume, an error.");
            }
            else
            {
                App_Announce_Event ("Paused Time Event resumed, not an error.");
            }
            break;
        case ssA_Runfsm_State_agencying :
            App_Announce_Event ("Agencying Time Event is busy, not an error.");
            break;
        case ssA_Runfsm_State_flaw      :
            App_Announce_Event ("Agencying Time Event state is flawed, an error.");
            break;
        default :
            App_Announce_Event ("Agencying Time Event state is invalid, an error.");
            break;
    }   // switch on RunFSM state
}   // AppLoop_ssTEA_Interface
// =================================================================================================
// Events: definition, launch into participation in ssTEA Agency FSMs, actions taken given agency.
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// This encapsulates the definition and launching within ssTEA of the Time Event and the Data Event.
// -------------------------------------------------------------------------------------------------
ssE_EvResult_t App_EventLauncher (void)
{
    ssUI_db_pEvApi_t    TimeEvent_pEvApi;
    ssUI_db_pEvApi_t    DataEvent_pEvApi;
    ssE_EvResult_t      EvResult;

    App_Announce_Event ("App_EventLauncher: Time Event and Data Event");

    TimeEvent_pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (TIME_EVENT_EVAPI);
    EvResult = App_TimeEvent_Define (TimeEvent_pEvApi);
    if (EvResult != ssE_EvResult_OK_go)
    {
        App_Announce_App ("Time Event Define error; App Launcher failed");
        return (EvResult);
    }

    DataEvent_pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (DATA_EVENT_EVAPI);
    EvResult = App_DataEvent_Define (DataEvent_pEvApi);
    if (EvResult != ssE_EvResult_OK_go)
    {
        App_Announce_App ("Data Event Define error; App Launcher failed");
        return (EvResult);
    }

    EvResult = App_TimeEvent_Launch (TimeEvent_pEvApi);
    if (EvResult != ssE_EvResult_OK_go)
    {
        App_Announce_App ("Time Launch failed");
        return (EvResult);
    }
    ssUI_dbOp_Show_OneEvApi (TimeEvent_pEvApi);

    EvResult = App_DataEvent_Launch (DataEvent_pEvApi);
    if (EvResult != ssE_EvResult_OK_go)
    {
        App_Announce_App ("Time Launch OK, Data Launch failed");
        return (EvResult);
    }
    ssUI_dbOp_Show_OneEvApi (DataEvent_pEvApi);

    App_Announce_App ("Time and Data Launch OK; App Launch success");
    return (EvResult);
}   // App_EventLauncher
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// This defines an Event FSM in the language ssTEA uses to manage an Event within an operating FSM.
// -------------------------------------------------------------------------------------------------
ReadOnly pAsciiA_t  pcTimeEvent             = S("TimeEvent");
ssUI_Token_t        myTimeEventTkn          = { pcTimeEvent     , 9, NoBananas };

ssE_EvResult_t App_TimeEvent_Define (ssUI_db_pEvApi_t pEvApi)
{
    ssTEA_pApiSig_t         pApiSig;                // create local expressions for an object within
    ssE_pAboutEv_t          ssE_pAboutEv;           //   the EvApi data pointed to by the caller

    ssE_EvResult_t          EvResult = ssE_EvResult_OK_go;

    // ---------------------------------------------------------------------------------------------
    // NOTE: ssUI's free supply of EvApi data has initialization for some fields that need updating
    // ---------------------------------------------------------------------------------------------
    pEvApi->pEvApiNameTkn_App = &myTimeEventTkn;
    pEvApi->pEvFuncToUse = &App_TimeEvent_Operate;

    App_Announce_App ("Time Event Launcher Api FSM On Request : ");
    if (!ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgApifsm_On))
    {
        App_Announce_ssTEA ("Request to set Time Event Agency API FSM state to On failed, an error.");
        return (ssE_EvResult_notOK_state);
    }

    // ---------------------------------------------------------------------------------------------
    // The signal carrier for the Event API to ssTEA has a pointer to the ssTEA data About the Event.
    // Change focus to ssTEA's view of or about the event.  We know our App is trusted, as chosen
    // by the Simplest Config, we know the pointer to the AboutEv was established by ssTEA's Api On.
    // ---------------------------------------------------------------------------------------------
    // NOTE: This complex ssTEA detail matters only when changing from one style to the other.  Later.
    // ---------------------------------------------------------------------------------------------
    // NOTE: This is a result of the design of ssUI supporting N Events inherently for the App to use,
    // NOTE: the pointer must be initialized in the EvApi by the App before the Agency Api FSM is ON.
    // NOTE: A SimpleSal App allocating and managing the EvApi data structures does not need this.
    // ---------------------------------------------------------------------------------------------
    pApiSig = pEvApi->pssTEA_ApiSig;
    ssE_pAboutEv = pApiSig->ssE_pAboutEv;

    // ---------------------------------------------------------------------------------------------
    // The App loop (in this forced example) turns On the LED every N seconds (example: 5 seconds).
    // With the LED On, the App loop changes the OccursAt Time and period and resumes the Time Event.
    // ---------------------------------------------------------------------------------------------
    // The Time Event turns Off the LED when the period of Time completes (example: 3 seconds).
    // The Time Event, while agencying, waits to be granted Agency.  The period between App loop's
    // LED On and Event's LED Off is the period of Time "On Duty"; as a percentage "the Duty Cycle".
    // ---------------------------------------------------------------------------------------------
    // Why? An off|on|off cycle repeating has a period On and a period Off; an oscillating signal
    // has a Duty Cycle of 50%.  Power management in SOC chips is based on reducing the Duty cycle
    // (as % of a power signal cycle) down to ONLY that needed, by controlling the power duty cycle.
    // ---------------------------------------------------------------------------------------------
    // NOTE: done by Api FSM On:  pEvApi->pssTEA_ApiSig->ssE_pAboutEv->pEvFunc = pEvApi->pEvFuncToUse;
    // ---------------------------------------------------------------------------------------------
    ssE_pAboutEv->Runfsm_EvType = ssE_EvType_Time;
    ssT_mathOp_P1getsP2 (&ssE_pAboutEv->OccursAt, ssT_gpTime_Current);  // immediate on being resumed
    ssE_pAboutEv->recurs = true;
    ssE_pAboutEv->recursFromTrue = true;
    ssT_mathOp_P1getsP2 (&ssE_pAboutEv->Period, ssT_gpTime_1sc);        // recur each second
    ssE_pAboutEv->App_pEventData = (EvEx_App_pEventData_t) &pEvApi->App_EventData;

    App_Announce_App ("Time Event Agency API On; TimeEvent Defined");
    App_Announce_App ("Event Occurs At ");
    ss_uiOp_Show_Time (&ssE_pAboutEv->OccursAt, lfY);

    return (EvResult);
}  // App_TimeEvent_Define
// -------------------------------------------------------------------------------------------------
// This "launch the App Event into ssTEA's FSM control", using the definition created by the App.
// -------------------------------------------------------------------------------------------------
ssE_EvResult_t App_TimeEvent_Launch (ssUI_db_pEvApi_t pEvApi)
{
    ssE_EvResult_t  EvResult = App_Launch_in_ssTEA (pEvApi);

    // ---------------------------------------------------------------------------------------------
    // A Launched Time Event is by definition in the Agencying state.  The NEXT moment in Time the
    // Launched Time Event COULD be granted Agency by ssTEA is the NEXT moment in Time Agency is
    // granted to ssTEA by the App's loop, and the Event is considered and granted Agency by ssTEA.
    // ---------------------------------------------------------------------------------------------
    // For the purposes of this (forced) example, and to make the reader think about Time, a flawed
    // Time Event model is forced.  Normal use of Time Events is to OccurAt one or both transitions;
    // the Period for these transitions remains constant so the Event simply recurs in ssTEA's view.
    // Also forced is the Event's request on exit to be returned to the Paused state from Agencying.
    // ---------------------------------------------------------------------------------------------
    if (EvResult == ssE_EvResult_OK_go)
    {
        if (ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgRunfsm_Pause))
        {
            App_Announce_ssTEA ("Agencying Time Event paused");
        }   // Pause succeeded
        else
        {   // Pause failed
            App_Announce_ssTEA ("Error: Agency Api FSM failed to pause while Agencying");
            EvResult = ssE_EvResult_notOK_API;
        }   // Pause failed
    }   // Launch in ssTEA succeeded
    else
    {   // Launch in ssTEA failed
        App_Announce_ssTEA ("Error: Agency Api FSM Launch failed");
    }   // Launch in ssTEA failed

    return (EvResult);
}  // App_TimeEvent_Launch
// -------------------------------------------------------------------------------------------------
// The content here that is ssTEA-related software: 1) makes sure not init state; 2) return Pause.
// The content that is App-related software: 1) signal Data Event with data; turn the LED off.
// -------------------------------------------------------------------------------------------------
// Note that this Event does not refer to About Event data of its own, but that of the Data Event.
// -------------------------------------------------------------------------------------------------
ssE_EvResult_t App_TimeEvent_Operate (ssE_pAboutEvVoid_t param1, ssT_pTime_t pCurrentTime)
{
    ssUI_db_pEvApi_t    DataEvent_pEvApi;
    ssE_EvResult_t      ReturnResult = ssE_EvResult_OK_go;

    if (param1 == pVoidEvParam1Null)
    {
        App_Announce_Event ("App_TimeEvent_Operate in init state...");
        return (ReturnResult);
    }

    mesa_uiOp_LEDoff ();
#ifdef APP_OPTIN_ANNOUNCE_EVENT
    ss_uiOp_Show_Time (ssT_gpTime_Current, lfY);
    App_Announce_Event ("App_TimeEvent_Operate in agency state turned LED off...");
    App_Announce_Event ("App_TimeEvent_Operate in agency state sending msg to Data Event...");
#endif  // APP_OPTIN_ANNOUNCE_EVENT

    // ---------------------------------------------------------------------------------------------
    // One method for communicating between the App's context and the Event's context is to simply
    // refer to variables within the scope or view of the software: global to the App and the Event.
    // In this case, the global variable is the space allocated for this Event by the App in EvApi.
    // ---------------------------------------------------------------------------------------------
    DataEvent_pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (DATA_EVENT_EVAPI);
    (void) ssUI_AaOp_pP1_gets_pP2max (&DataEvent_pEvApi->App_EventData.Data[0],
                   S("msg from Time Event: LED turned off...1234567890"), APP_DATA_MAX_I);

    // ---------------------------------------------------------------------------------------------
    // The Time Event sends a signal to ssTEA to resume the Data Event, using the Data Event's API.
    // ---------------------------------------------------------------------------------------------
    if (!ssUI_apiSignalOp_Emit (DataEvent_pEvApi, ss_ApiSigMsgValue_AgRunfsm_Resume))
    {
        App_Announce_ssTEA ("attempt to signal Data Event resume by LED Off failed");
        return (ssE_EvResult_notOK_state);
    }

    ReturnResult = ssE_EvResult_OK_pauseMe;
    return (ReturnResult);
}   // App_TimeEvent_Operate
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------------
ReadOnly pAsciiA_t  pcDataEvent             = S("DataEvent");
ssUI_Token_t        myDataEventTkn          = { pcDataEvent     , 9, NoBananas };

ssE_EvResult_t App_DataEvent_Define (ssUI_db_pEvApi_t pEvApi)
{
    ssTEA_pApiSig_t         pApiSig;                // create a local expression for an object within
    ssE_pAboutEv_t          ssE_pAboutEv;           // same

    ssE_EvResult_t          EvResult = ssE_EvResult_OK_go;

    // ------------------------------------ ---------------------------------------------------------
    // NOTE: ssUI's free supply of EvApi data has initialization for some fields that need updating.
    // NOTE: see the function App_TimeEvent_Define for detailed explanation of pointer to Events.
    // ---------------------------------------------------------------------------------------------
    pEvApi->pEvApiNameTkn_App = &myDataEventTkn;
    pEvApi->pEvFuncToUse = &App_DataEvent_Operate;

    App_Announce_App ("Data Event Launcher Api FSM On Request");
    if (!ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgApifsm_On))
    {
        App_Announce_App ("Request to set Data Event API FSM state to On failed.");
        return (ssE_EvResult_notOK_state);
    }

    // ---------------------------------------------------------------------------------------------
    // The signal carrier for the Event API to ssTEA has a pointer to the ssTEA data About the Event.
    // ---------------------------------------------------------------------------------------------
    pApiSig = pEvApi->pssTEA_ApiSig;
    ssE_pAboutEv = pApiSig->ssE_pAboutEv;

    // ---------------------------------------------------------------------------------------------
    // Everything about a Data Event's data is defined by the Data Event: format, location, alloc.
    // ---------------------------------------------------------------------------------------------
    ssE_pAboutEv->Runfsm_EvType = ssE_EvType_Data;
    ssE_pAboutEv->App_pEventData = (EvEx_App_pEventData_t) &pEvApi->App_EventData;

    App_Announce_App ("Data Event Agency API On; DataEvent Defined");
    return (EvResult);
}  // App_DataEvent_Define
// -------------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------------
ssE_EvResult_t App_DataEvent_Launch (ssUI_db_pEvApi_t pEvApi)
{
    ssE_EvResult_t  EvResult = App_Launch_in_ssTEA (pEvApi);

    if (EvResult == ssE_EvResult_OK_go)
    {
        if (ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgRunfsm_Pause))
        {
            App_Announce_ssTEA ("Agencying Data Event paused");
        }   // Pause succeeded
        else
        {   // Pause failed
            App_Announce_ssTEA ("Error: Agency Api FSM failed to pause while Agencying");
            EvResult = ssE_EvResult_notOK_API;
        }   // Pause failed
    }   // launched now agencying

    return (EvResult);
}  // App_DataEvent_Launch
// -------------------------------------------------------------------------------------------------
// The content here that is ssTEA-related software: 1) makes sure not init state; 2) return Pause.
// The content that is App-related software: 1) emit the bytes given to the output device.
// -------------------------------------------------------------------------------------------------
ssE_EvResult_t App_DataEvent_Operate (ssE_pAboutEvVoid_t param1, ssT_pTime_t pCurrentTime)
{
    ssE_pAboutEv_t      ssE_pAboutEv;      // valid after param1 is qualified as non-NULL
    App_pEventData_t    local_App_pEventData;

    ssE_EvResult_t      ReturnResult = ssE_EvResult_OK_pauseMe;

    if (param1 == pVoidEvParam1Null)
    {
        App_Announce_Event ("App_DataEvent_Operate in init state...");
        return (ReturnResult);
    }

    App_Announce_Event ("App_DataEvent_Operate in agency state emits Time Event data...");

    // ---------------------------------------------------------------------------------------------
    // One method for communicating between the App's context and the Event's context is a pointer
    // to the App's data tucked away in the About Event data given to the Event when Agency granted.
    // This supports an Event that is given the information about the device to address by the App.
    // ---------------------------------------------------------------------------------------------
    ssE_pAboutEv = (ssE_pAboutEv_t) param1;
    local_App_pEventData = (App_pEventData_t) ssE_pAboutEv->App_pEventData;
#ifdef APP_OPTIN_ANNOUNCE_EVENT
    App_Announce_Event (&local_App_pEventData->Data);
    ss_uiOp_Show_Time (ssT_gpTime_Current, lfY);
#endif  // APP_OPTIN_ANNOUNCE_EVENT

    ReturnResult = ssE_EvResult_OK_pauseMe;
    return (ReturnResult);
}   // App_DataEvent_Operate
// =================================================================================================
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// This function must be instantiated by the App in order to satisfy ssUI's reference when the
// App is built, but the function does not have to do anything with the user input provided.
// -------------------------------------------------------------------------------------------------
void App_HeyProcessThis (pAsciiA_t  pReceivedInput)
{
    mesa_uiOp_emit_newline ();
    ss_uiOp_emit_lbld_AsciiA (S("App's command input processor called with:"), pReceivedInput);

    if (ssUI_BufferOnlyHas_appui (pReceivedInput))
    {
        // -----------------------------------------------------------------------------------------
        // agency has been granted by ssTEA_App to the App to control the Ascii UI.
        // ssTEA_App is comprised of the Apps and the ssUI interface used to manipulate the Apps and ssTEA
        // -----------------------------------------------------------------------------------------
        ss_uiOp_qBanner (lfN, "App will now control the UI", lfY);
        mesa_Ascii_RO_state = mesa_RO_state_App;
    }
    else
    {
        // -----------------------------------------------------------------------------------------
        // agency has been granted by the App to ssUI to control the UI
        // -----------------------------------------------------------------------------------------
        if (ssUI_BufferOnlyHas_ssui (pReceivedInput))
        {
            mesa_Ascii_RO_state = mesa_RO_state_SimpleSal;
        }
    }
} // App_HeyProcessThis

// end of file: app_events.ino



