/* -- SimpleSal: ssTEA, ssUI, and ssIO | Copyright (C) 2025, 2026 TruSoft Computing LLC |  All rights reserved. --
   This software is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
   This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
   ---------------------------------------------------------------------------------------------------
 *
 * app-events.ino       Arduino main program demonstrating Time and Data Events based on ssTEA.
 *
 **************************************************************************************************/
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// This is a SimpleSal App developed and published by TSC LLC to demonstrate SimpleSal App features.
// -------------------------------------------------------------------------------------------------
// This App demonstrates the level of complexity SimpleSal supports: more than loop, less than RTOS.
// SimpleSal's Time and Event API helps solve complex problems a looping baremetal algorithm can't.
// Real device or system software problems are advanced implementations of the ideas within ssTEA.
// The solutions are simplified versions of RTOS or OS algorithms: Time- and Event-based software.
// -------------------------------------------------------------------------------------------------
// This minimum App demonstrates software in a legacy App interacting with ssTEA and ssUI real-time.
// The App's (forced) design: App's loop emits signals causing ssTEA to grant Events Agency.
// -------------------------------------------------------------------------------------------------
// Imagine a dangerously stupid machine which signals every 5 seconds "I am executing my software",
// by asserting a value on a shared communication link such as a wire on a board or a network port.
// If the dangerously stupid machine does not signal it is working, the App powers off the machine.
// Each time the App reads a signal from the machine, the signal is turned off, ready for the next.
// -------------------------------------------------------------------------------------------------
// The demonstration of ssTEA includes
//
//      a Time Event to check the state at some point in Time, a Time Event that does not recur.
//      a Data Event to display data generated by the Time Event, when signaled by the Time Event.
//      a Time Event that recurs each second, each recurrence decrements a counter if nonzero; if
//           counter transitions from nonzero to zero: ssUI is used to show the current statistics.
// -------------------------------------------------------------------------------------------------
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// TSC LLC has a software strategy: identify what is true about all processors running software
// then hide the small differences with technical solutions in the build environment and software.
// The #defines here referenced by the ssTEA software are a technical solution in the software.
// -------------------------------------------------------------------------------------------------
// Consider all of the components required to produce, distribute, support, and use an application.
// Software portability across build environments (compilers, memory maps, allocations) may be
// managed at the very highest level by separating Arduino, Linux, Windows, RTOS, barebones, etc.
// -------------------------------------------------------------------------------------------------
#define     HOST_ONEOF_hostOS_Is_Arduino

// -------------------------------------------------------------------------------------------------
// Each platform has a variety of memory types; control over what goes where is often in the C code.
// For example, removing "static" from the ReadOnly #define might move Ascii constants: Flash to RAM.
// -------------------------------------------------------------------------------------------------
#define     ReadOnly    static

// -------------------------------------------------------------------------------------------------
// Software portability across Time from the same human brain requires some words remain constant.
// Some HOST build environments that define boolean and Null can be quite cranky about a re-define.
// -------------------------------------------------------------------------------------------------
#define     HOST_ONEOF_ssHL_defines_boolean
#define     HOST_ONEOF_ssHL_defines_Null

// -------------------------------------------------------------------------------------------------
// The definition of the simplest configuration depends on the file the build tool finds and uses,
// the only path requirement within ssTEA is that the compiler find the directory "SimpleSal\".
// The ability to set the path the compiler uses to lookup included files is a technical solution.
// -------------------------------------------------------------------------------------------------
// This SimpleSal App is meant to build with "SimpleSal\ss_configuration.start" with the extension
// changed to ".h". The include shows the "ss_configuration.h" is expected in the App directory.
// -------------------------------------------------------------------------------------------------
#define     SS_OPTIN_INCLUDE_SSTEA
#define     SS_ACCEPT_SIMPLEST_CONFIG

#define     SSE_ACTIVE_EVENTS_CT_REQUESTED       (6)

#include "ss_configuration.h"

// -------------------------------------------------------------------------------------------------
// The simplest configuration selection to show build options can be undone with #undef; this works
// for any definition that is NOT used IN ss_configuration.h to extend the configuration definition.
// -------------------------------------------------------------------------------------------------
#undef      SS_OPTIN_SHOW_BUILD_OPTIONS

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// Software portability across platforms requires operational levers built in that hide differences.
// The levers are defined in "mesa_min_dcl" and "mesa_min_def"; ssTEA uses micros() and Ascii.
// -------------------------------------------------------------------------------------------------
// Only the output services of ssUI are used in this App; no Ascii input is detected or consumed.
// The baud rate given to the serial device is specified in "mesa_min_def.h": THIS_BUILDS_BAUD_RATE.
// -------------------------------------------------------------------------------------------------
// This SimpleSal App is meant to build with "mesa_min_dcl.start" with extension changed to ".h".
// -------------------------------------------------------------------------------------------------
#include "mesa_min_dcl.h"

// -------------------------------------------------------------------------------------------------
// Using ssTEA data types, App data types for Events may be declared HERE.  ssTEA Event Agency uses
// data "about" the Event; within that data about the Event is the App data accessed by the Event.
// -------------------------------------------------------------------------------------------------
// An Event communicating with an App or other Events uses the App Event Data as a signal carrier.
// -------------------------------------------------------------------------------------------------
// This is one of the "moderately complex" software concepts required to write signaling software:
//   there are many kinds of signal/sensor devices and any number of each in a single application.
// The data structures used as an organizing concept "about" any object are signal carriers; the
// organization of the signal carriers and the relationship they support influences the algorithms.
// -------------------------------------------------------------------------------------------------
#include "SimpleSal\ssTEA\ssTEA_data_dcl.h"

#define     APP_DATA_ALLOC      (40)
#define     APP_DATA_MAX_I      (APP_DATA_ALLOC-1)

typedef struct App_EventDataDesc_s
{
    int                 Stats_CalcPeriod_ms;        // every X ms, perform calculation, new result
    int                 Stats_CalcPeriod_ct;        // in this period, the current ms count is X
    int                 Stats_EmitPeriod_ms;        // every X ms, output the current result value
    int                 Stats_EmitPeriod_ct;        // in this period, the current ms count is X

    AsciiA_t            Data[APP_DATA_ALLOC];
}   App_EventDataDesc_t,  *App_pEventDataDesc_t;

typedef App_EventDataDesc_t      App_EventData_t;       // referenced by ssTEA data type directly
typedef App_pEventDataDesc_t     App_pEventData_t;
#define App_pEventDataNull       ((App_pEventData_t) NULL)

// -------------------------------------------------------------------------------------------------
// The UI shared between the App and ssUI is simplified here by ssUI sending "app ..." input here.
// Unless ssUI is completely out of the build (data, input, output, menus) a Hey! reference is made.
// -------------------------------------------------------------------------------------------------
void        App_HeyProcessThis (pAsciiA_t  pReceivedInput);

// -------------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------------
#include "SimpleSal\ss_include_dcl.h"

// -------------------------------------------------------------------------------------------------
// This SimpleSal App is meant to build with "mesa_min_def.start" with extension changed to ".h".
// -------------------------------------------------------------------------------------------------
#include "mesa_min_def.h"

// -------------------------------------------------------------------------------------------------
// Because ssUI co-exists with the App, it needs to begin existence with Resources correlated to App
// -------------------------------------------------------------------------------------------------
#define  ssUI_Default_LED_RO_state          mesa_RO_state_App
#define  ssUI_Default_LED_RO_substate       mesa_RO_substate_none
#define  ssUI_Default_Ascii_RO_state        mesa_RO_state_App
#define  ssUI_Default_Ascii_RO_substate     mesa_RO_substate_none
#define  ssUI_Default_Matrix_RO_state       mesa_RO_state_App
#define  ssUI_Default_Matrix_RO_substate    mesa_RO_substate_none

// -------------------------------------------------------------------------------------------------
// Allocations of data and definition of functions with parameters, as declared by ss_include_dcl.h
// -------------------------------------------------------------------------------------------------
#include "SimpleSal\ss_include_def.h"

// -------------------------------------------------------------------------------------------------
// The interfaces to the mesa, ssTEA and ssUI are now fully referenceable by App software.
// -------------------------------------------------------------------------------------------------

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// The included file has helpers for Apps interacting with ssTEA through ssTEA's software interface.
// The function definitions are the App's functions making use of the API to interact with ssTEA.
// They represent the three phases of life of an FSM within ssTEA: definition, launch, operation.
// The term "activation" means "all three phases completed so the Event is operating as defined".
// -------------------------------------------------------------------------------------------------
#include "api_ssTEA_dcl.h"

// -------------------------------------------------------------------------------------------------
// Knowledge held by the software developer about the software is deepest in the App, then about the
// Events, and then finally the detailed vocabulary and grammar of ssTEA's Time and Agency data.
// Debugging? enable App's description of success/failure, then Event algorithm's, then ssTEA's.
// -------------------------------------------------------------------------------------------------
// This is just a compilation trick of ssHL C or C++ that hides whether the software exists or not.
// All of the references in the software remain the same whether selecting announce activity or not.
// When the compiler finds the reference, and the selection is "not announce", nothing is compiled.
// -------------------------------------------------------------------------------------------------
// #define APP_OPTIN_ANNOUNCE_APP
// #define APP_OPTIN_ANNOUNCE_EVENT
// #define APP_OPTIN_ANNOUNCE_SSTEA

#ifdef APP_OPTIN_ANNOUNCE_APP
#define App_Announce_App(xpThis)    { mesa_uiOp_emit_qAsciiA (xpThis); mesa_uiOp_emit_newline (); }
#else  // not APP_OPTIN_ANNOUNCE_APP
#define App_Announce_App(xthis)
#endif // APP_OPTIN_ANNOUNCE_APP

#ifdef APP_OPTIN_ANNOUNCE_EVENT
#define App_Announce_Event(xpThis)  { mesa_uiOp_emit_qAsciiA (xpThis); mesa_uiOp_emit_newline (); }
#else  // not APP_OPTIN_ANNOUNCE_EVENT
#define App_Announce_Event(xpThis)
#endif // APP_OPTIN_ANNOUNCE_EVENT

#ifdef APP_OPTIN_ANNOUNCE_SSTEA
#define App_Announce_ssTEA(xpThis)  { mesa_uiOp_emit_qAsciiA (xpThis); mesa_uiOp_emit_newline (); }
#else  // not APP_OPTIN_ANNOUNCE_SSTEA
#define App_Announce_ssTEA(xthis)
#endif // APP_OPTIN_ANNOUNCE_SSTEA

// -------------------------------------------------------------------------------------------------
// the helpers for the API interface to ssTEA participate in the announcement choices by the App.
// -------------------------------------------------------------------------------------------------
#include "api_ssTEA_def.h"

// -------------------------------------------------------------------------------------------------
// The interfaces to everything outside the App are now fully referenceable by App software.
// -------------------------------------------------------------------------------------------------

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// The App's ssTEA functionality is defined AFTER ssTEA knowledge is included; this function hides
// that dependency from the App loop. As originally written, the App loop only knew about the mesa.
// -------------------------------------------------------------------------------------------------
// The functions whose address are used as a pointer (App_xEvent_operate) must be declared.
// -------------------------------------------------------------------------------------------------
void    AppLoop_ssTEA_Interface (void);

ssE_EvResult_t  App_EventLauncher (void);

ssE_EvResult_t  App_TimeEvent_Define     (ssUI_db_pEvApi_t    pEvApi);
ssE_EvResult_t  App_TimeEvent_Launch     (ssUI_db_pEvApi_t    pEvApi);
ssE_EvResult_t  App_TimeEvent_Operate    (ssE_pAboutEvVoid_t  param1, ssT_pTime_t pCurrentTime);

ssE_EvResult_t  App_DataEvent_Define     (ssUI_db_pEvApi_t    pEvApi);
ssE_EvResult_t  App_DataEvent_Launch     (ssUI_db_pEvApi_t    pEvApi);
ssE_EvResult_t  App_DataEvent_Operate    (ssE_pAboutEvVoid_t  param1, ssT_pTime_t pCurrentTime);

ssE_EvResult_t  App_StatsEvent_Define    (ssUI_db_pEvApi_t    pEvApi);
ssE_EvResult_t  App_StatsEvent_Launch    (ssUI_db_pEvApi_t    pEvApi);
ssE_EvResult_t  App_StatsEvent_Operate   (ssE_pAboutEvVoid_t  param1, ssT_pTime_t pCurrentTime);

// -------------------------------------------------------------------------------------------------
// allocation of per-Event data in ssTEA and ssUI is all based on SSE_ACTIVE_EVENTS_CT_REQUESTED.
// These defines simply assign the ownership of each ssUI EvApi data structure to an array Index.
// This model supports the address of data being computed at run time by a function, not build time.
// -------------------------------------------------------------------------------------------------
// F14B56      specific configurations of EvApi allocations cause a hard fault in the App
//    requesting allocation of 3 EvApis and use the order 0,1,2: a quiet hard fault occurs.
//    changing order from 0,1,2 to 2,1,0: changed behavior from quiet brick to fault display.
//      address being accessed ends in 0xA, which is 10, which is not a multiple of 4.
//      LR link register is 67C1, the address of the caller of the code causing the fault
//    requesting allocation of 6 EvApis and using 2,1,0 or 2,1,0 order: hard fault does NOT occur.
//      this strongly suggests that a reference beyond the EvApi[0,1,2] is made by the statistics,
//      referring to memory after EvApi[2] ends hits EvApi[3,4,5]; instead of another variable.
// -------------------------------------------------------------------------------------------------
#define     TIMEevent_EVENT_API             (2)
#define     DATAevent_EVENT_API             (1)
#define     STATSevent_EVENT_API            (0)

// -------------------------------------------------------------------------------------------------
// The (forced) App tracks the full cycle using millisecond Timekeeping, the Duty cycle using ssTEA.
// ------------------------------------------------------------------------------------------------
// An alternative allocation of ssTEA variables, as supported by ssTEA, is to use ssUI's free ones.
// ssTEA also provides a variety of constant Time definitions of useful periods of Time for the App.
// -------------------------------------------------------------------------------------------------
#define     App_FullCycleMillis     (SST_MSECS_PER_SEC * 5)

#define     App_Duty_OnTime         ssT_gpTime_3sc
#define     App_Duty_OffTime        ssT_gpTime_2sc

#define     App_StartTimeFromNow    ssT_gpTime_1sc

#define     App_CalcPeriod          50          // frequent calculation means smaller deltas
#define     App_EmitPeriod          500         // slower emission seems to show more variance

#define     APP_ONEOF_TIME_START_BUILDTIME
// #define     APP_ONEOF_TIME_START_ZERO

// -------------------------------------------------------------------------------------------------
// Useful Event API data can be displayed, or not displayed, based on a compile-time choice here.
// -------------------------------------------------------------------------------------------------
// #define APP_ONEOF_DISPLAY_EVAPI_DEBUG_Y
#define APP_ONEOF_DISPLAY_EVAPI_DEBUG_N

#ifdef APP_ONEOF_DISPLAY_EVAPI_DEBUG_Y
#define debug_Show_OneEvApi(xpEvApi) ssUI_dbOp_Show_OneEvApi (xpEvApi)
#endif  // APP_ONEOF_DISPLAY_EVAPI_DEBUG
#ifdef APP_ONEOF_DISPLAY_EVAPI_DEBUG_N
#define debug_Show_OneEvApi(xpEvApi)
#endif  // APP_ONEOF_DISPLAY_EVAPI_DEBUG

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// This SimpleSal App demonstrates the use of Events in various ways to write a Signal Algorithm.
// -------------------------------------------------------------------------------------------------
ReadOnly    pAsciiA_t   pcMsg_AppInit       = S("<mesa [P39] and App [app-events] initializing...>");

#ifdef APP_OPTIN_ANNOUNCE_APP

ReadOnly    pAsciiA_t   pcMsg_InitBanner    = S("SimpleSal App using Events initializing ssTEA...");
ReadOnly    pAsciiA_t   pcMsg_AppCoexists   = S("SimpleSal App co-existing with ssTEA...");
ReadOnly    pAsciiA_t   pcMsg_AppLauncherFailed = S("App Launcher failed");

#else   // not APP_OPTIN_ANNOUNCE_APP

ReadOnly    pAsciiA_t   pcMsg_InitBanner        = pAsciiANull;
ReadOnly    pAsciiA_t   pcMsg_AppCoexists       = pAsciiANull;

#endif // APP_OPTIN_ANNOUNCE_APP

#define APP_BUFFER_ALLOC  100
#define APP_BUFFER_MAX_I  (APP_BUFFER_ALLOC-1)

// -------------------------------------------------------------------------------------------------
// The Time Keeping model for the App is retained from the original non-ssTEA App; a legacy model.
// Where previously the App software would run within Loop and count milliseconds, in the ssTEA
// model Events run periodically at a constant rate and the Event grants Agency to the legacy model.
// -------------------------------------------------------------------------------------------------
#define     App_pStats_Period_Emit    ssT_gpTime_1ms

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// The function is owned by the App and specific to the App.  Co-existence with ssTEA starts here.
// For example, configure events and start Time and Agency in support of the App's use of ssTEA.
// The starting position is determined by values is ssTEA_control, as set by App during setup.
// This is the software that will be added to an arduino project to incorporate ssTEA and ssUI.
// -------------------------------------------------------------------------------------------------
void App_ss_launch (void)
{
    ssT_Time_t  localTimeVar;
    AsciiA_t    localBuff[APP_BUFFER_ALLOC];

    ssTEA_control.Time_state = ssTEA_state_stopped;
    ssTEA_control.Time_base = ssTEA_Time_base_reality;
    ssTEA_control.Agency_state = ssTEA_state_stopped;
    ssTEA_control.Agency_pace = ssTEA_Agency_pace_period;
    ssTEA_control.Agency_period = ssTEA_Agency_pace_period_minimum;

    // ---------------------------------------------------------------------------------------------
    // ssTEA generates many messages at runtime when asked to, WHEN the messages have been OPTIN'd.
    // Output is gated at runtime (control.Show), WHEN the ss_configuration value enables (OPTIN).
    // ---------------------------------------------------------------------------------------------
    ssTEA_control.Show_Path = false;
    ssTEA_control.Show_Signals = false;
    ssTEA_control.Show_Cause = false;
    ssTEA_control.Show_Facts = false;

    ssUI_control.BeVerbose = false;

    // if a hard fault occurs in ssTEA, the serial output may not get a chance to send it all
    mesa_uiOp_emit_qAsciiA ("<ssTEA init...");
    ssTEA_InitState ();
    mesa_uiOp_emit_qAsciiA ("success>");
    mesa_uiOp_emit_newline ();

    mesa_uiOp_emit_qAsciiA ("<ssUI init...");
    ssUI_InitState ();
    mesa_uiOp_emit_qAsciiA ((ssUI_control.BeVerbose) ? "{verbose}" : "{quiet}");
    mesa_uiOp_emit_qAsciiA ("success>");
    mesa_uiOp_emit_newline ();

    // ---------------------------------------------------------------------------------------------
    // This function is build-controlled: whether it has content or not depends on build options.
    // ---------------------------------------------------------------------------------------------
    App_BuildOp_Show_Build ();

    // ---------------------------------------------------------------------------------------------
    // App is ready for App_loop to run; ssTEA is configured  ready for ssTEA_loop: "hello, world".
    // ---------------------------------------------------------------------------------------------
    if (ssT_stampOp_TimeOfBuild_AsciiToTime (localBuff))
    {
        mesa_uiOp_emit_qAsciiA ("Time built:");
        ss_uiOp_Show_Time (ssT_gpTime_Built, lfY);

        // ---------------------------------------------------------------------------------------------
        // ssT, the Time component of ssTEA, defines useful Time variables with valid values.  The side-
        // effect problem is useful doesn't mean used by every App; reference to stop compiler warnings.
        // The compiler cannot tell whether the variable localTimeVar value is actually used; it is not.
        // ---------------------------------------------------------------------------------------------
        ssT_mathOp_P1getsP2 (&localTimeVar, ssT_gpTime_5sc);
        ssT_mathOp_P1getsP2 (&localTimeVar, ssT_gpTime_10sc);
    }

    // ---------------------------------------------------------------------------------------------
    // The only difference between a clock display and a timer display is the timer starts at zero.
    // ---------------------------------------------------------------------------------------------
#ifdef APP_ONEOF_TIME_START_BUILDTIME
    ssT_mathOp_P1getsP2 (ssT_gpTime_Current, ssT_gpTime_Built);
#endif // APP_ONEOF_TIME_START_BUILDTIME

    ssTEA_control.Time_state = ssTEA_state_running;
    ssTEA_control.Agency_state = ssTEA_state_running;

    ss_uiOp_Show_ssTime_state ();
    ss_uiOp_Show_ssAgency_state ();

    // ---------------------------------------------------------------------------------------------
    // The ssTEA Api and Run FSMs are active; now activate the events within that ecosystem.
    // ---------------------------------------------------------------------------------------------
    App_EventLauncher ();

    ss_uiOp_Show_ssTime_state ();
    ss_uiOp_Show_ssAgency_state ();

} // App_ss_launch
// =================================================================================================
#define setup   App_setup

// #define  APP_OPTIN_SIGNAL_RUNNING
// #define  APP_OPTIN_SIGNAL_LOOPING

#ifdef APP_OPTIN_SIGNAL_LOOPING
#define LOOP_CT_HEARTBEAT     (1000000)     // how many of what thing is that anyway?
int App_Loop_Heartbeat;
#endif  //  APP_OPTIN_SIGNAL_LOOPING

void setup (void)       // the App's original setup function, ssTEA calls as App_setup.
{
    // this content was in the App's original setup function, copied here before adding SimpleSal
    /* original App */

#ifdef APP_OPTIN_SIGNAL_LOOPING
    App_Loop_Heartbeat = LOOP_CT_HEARTBEAT;         // the Init state is "count expires this loop"
#endif  //  APP_OPTIN_SIGNAL_LOOPING

    // this content added to the App's original setup function, co-existence has a price.
    mesa_Ascii_RO_state     = mesa_RO_state_App;
    mesa_Ascii_RO_substate  = mesa_RO_substate_none;

    mesa_uiOp_deviceInitialize ();

    mesa_gCtOf_1usThis1ms     = 0;      // this App only tries to be active every 1000 milliseconds
    mesa_gCtOf_1msThis100ms   = 0;      // mesa provides for ssUI which is not used here
    mesa_gCtOf_1msThisCycle   = 0;      // period: starting with off->on until the next off->on

    mesa_gCtOf_1msFreeRunning = 0;      // a calculated millis count rather than reading a chip reg

    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_qAsciiA (pcMsg_AppInit);
    mesa_uiOp_emit_newline ();

}   // setup            // the App's original setup function

#undef setup            // don't forget to forget #define

// the ssHL compiler has seen and compiled "App_setup", and has not yet seen anything called "setup".

// =================================================================================================
#define loop    App_loop

void loop (void)        // (the App's original loop function, ssTEA's loop calls as App_loop)
{
#ifdef APP_OPTIN_SIGNAL_LOOPING
    // ---------------------------------------------------------------------------------------------
    // the Init state is "count expires this loop", the "++" operation overflows the CT, heartbeat.
    // ---------------------------------------------------------------------------------------------
    if (++App_Loop_Heartbeat > LOOP_CT_HEARTBEAT)
    {
        App_Loop_Heartbeat = 0;
        mesa_uiOp_emit_1 (Ascii_Hash);
    }
#endif  //  APP_OPTIN_SIGNAL_LOOPING

    // ---------------------------------------------------------------------------------------------
    // Remember that the Arduino Host OS API calls "loop" and the trick used here puts ssTEA there.
    // ---------------------------------------------------------------------------------------------
    // This is a common Arduino Time Keeping algorithm: watch a microsecond counter change over Time.
    // Within Arduino, the function "micros ()" returns the number of microseconds since Time began.
    // This makes it possible to see how many microseconds occured since we last checked the Time.
    // The number of micros from one loop to the next, "loop1 to loop2", is calculated by ssTEA.
    // ---------------------------------------------------------------------------------------------
    // An App already tracking micros could of course continue to do so here.
    // ---------------------------------------------------------------------------------------------
    mesa_gCtOf_1usThis1ms += ssT_us_gLoop1toLoop2;

    // ---------------------------------------------------------------------------------------------
    // This "gate" the user's loop function (below) to only execute one time each 1000 microseconds.
    // ---------------------------------------------------------------------------------------------
    if (mesa_gCtOf_1usThis1ms <= SST_USECS_PER_MSEC)
    {
        return;
    }
    mesa_gCtOf_1usThis1ms = 0;

    // ---------------------------------------------------------------------------------------------
    // FreeRunning is a 32-bit number.  That number "modulo 1000" creates a remainder.  When the
    // remainder is zero, 1000 milliseconds have passed, or, 1 second.  Math is inherent in the
    // ability of the processor, math is what is was designed to do, math instructions are optimal.
    // ---------------------------------------------------------------------------------------------
    // The method does require the compiler store 32-bit values to compare with, somewhere nearby.
    // ---------------------------------------------------------------------------------------------
    mesa_gCtOf_1msFreeRunning++;
    if ((mesa_gCtOf_1msFreeRunning % SST_MSECS_PER_SEC) == 0)       // make the serial LED blink
    {
        // ssTEA and the App co-exist, so the deeply internal Agency state of ssTEA is easily seen.
        // if ssTEA Time and Agency FSMs are not operating, this App does not attempt to use them.
#ifdef APP_OPTIN_SIGNAL_RUNNING
        if (ssTEA_control.Agency_state == ssTEA_state_running)
        {
            mesa_uiOp_emit_1 (Ascii_ESC);
            if ((mesa_gCtOf_1msFreeRunning % (SST_MSECS_PER_SEC * 20)) == 0)
            {
                mesa_uiOp_emit_newline ();                              // move the display
            }
        }
#endif  // APP_OPTIN_SIGNAL_RUNNING
    }   // the App signal of activity while in loop is the serial port 1 value each 1 second

    // ---------------------------------------------------------------------------------------------
    // The count of millis this Cycle is not Free Running; but in fact the value of the Count is the
    // same value as the remainder that would have been computed based on the Free Running Count.
    // The valid range of values is constrained to the Cycle's millisecond range as decided by the App.
    // Finally, this solution considers any number over a maximum rather than specific maximum values.
    // ---------------------------------------------------------------------------------------------
    mesa_gCtOf_1msThisCycle++;
    if (mesa_gCtOf_1msThisCycle >= App_FullCycleMillis)
    {
        mesa_gCtOf_1msThisCycle = 0;

        // -----------------------------------------------------------------------------------------
        // ssTEA and the App co-exist, so the deeply internal Agency state of ssTEA is easily seen.
        // if ssTEA Time and Agency FSMs are not operating, this App does not attempt to use them.
        // -----------------------------------------------------------------------------------------
        if (ssTEA_control.Agency_state == ssTEA_state_running)
        {
            // Emulate the signal received from the stupidly dangerous machine that says "I'm alive".
            mesa_uiOp_LEDon ();

            // Schedule a Time Event in the App to turn the LED Off after a period of Time.
            AppLoop_ssTEA_Interface ();

        }   // ssTEA Agency running means ssTEA Time is running
        else
        {
            mesa_uiOp_emit_1 (Ascii_Tilde);
            mesa_uiOp_LEDoff ();        // the App controls a dangerous stupid machine, default off
        }
    }   // timeout occured
    // 1 millisecond of Time has gone by since we were last here in the algorithm

    // ---------------------------------------------------------------------------------------------
    // Any form of Time Keeping when dealing with humans needs to work at human speed: slowly. See
    // the more sophisticated SimpleSal Apps such as "app-fsmdemo" for examples of human device I/O.
    // This SimpleSal App does not depend on Ascii input received through ssUI so just do the math.
    // While ssTEA does not inherently manage 100ms units, ssUI gates Ascii read attempts to a
    // reasonable period between reads using this Time Keeping value which App_loop must maintain.
    // ---------------------------------------------------------------------------------------------
    mesa_gCtOf_1msThis100ms += 1;
    if (mesa_gCtOf_1msThis100ms >= 100)
    {
        mesa_gCtOf_1msThis100ms = 0;
    }   // 100ms period occured
}   // loop             // the App's original loop function, known as "App_loop"

#undef  loop            // don't forget to forget #define

// the ssHL compiler has seen and compiled "App_loop", and has not yet seen anything called "loop".

// =================================================================================================
#define ssTEA_setup  setup

void ssTEA_setup (void) // the one called by Arduino Host OS Api using the name "setup"
{
    // ---------------------------------------------------------------------------------------------
    // Call the original App's "setup", which was renamed to "App_setup" when the compiler found it.
    // This is software written without ssTEA so it may continue to execute before ssTEA is launched.
    // ---------------------------------------------------------------------------------------------
    App_setup ();

    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();

    ss_uiOp_pBanner (lfN, pcMsg_InitBanner, lfY);

    App_ss_launch ();

    ss_uiOp_pBanner (lfN, pcMsg_AppCoexists, lfY);

    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();
    mesa_uiOp_emit_newline ();

} // ssTEA_setup        // the one called by Arduino Host OS Api using the name "setup"

#undef ssTEA_setup      // don't forget to forget #define

// the ssHL compiler has seen and compiled "App_setup" and "setup"

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// "App_loop" is the original Arduino App's "loop" function, which will now be granted agency
// by ssTEA's "loop".  This was done by a #define trick in this file: rename the original App "loop"
// to "App_loop" and rename "ssTEA_loop" to "loop".  The result is the linker sees two functions:
// "App_loop" and "loop".  Instructions may be found elsewhere describing how to modify Original App.
// -------------------------------------------------------------------------------------------------
// This function should be usable as-is and used as-is.  This is where Time is perceived by ssTEA.
// When Agency granted by the Host OS has been intercepted here, Agency is granted first to ssTEA
// to manage Events, and finally Agency is granted to the App to react to the Events that occured.
// -------------------------------------------------------------------------------------------------
// ssTEA computes the consumption of Time by App Events inside ssTEA and by the App outside ssTEA.
// Because ssTEA bases all knowledge of Time on us_gLoop1toLoop2, software here that lies about the
// number of microseconds could basically make the entire ssTEA-based application into a Time-based
// simulation of the Time environment the algorithm interacts with.  Or something along those lines.
// -------------------------------------------------------------------------------------------------
#define ssTEA_loop loop

void ssTEA_loop (void)
{
    ssTEA_Time_MathEntry ();

    ssTEA_Agency_Root (ssT_us_gLoop1toLoop2, ssT_ms_gLoop1toLoop2);

    ssTEA_Time_MathExit ();

    App_loop ();

} // ssTEA_loop

#undef ssTEA_loop       // don't forget to forget #define

// the ssHL compiler has seen and compiled "App_loop" and "loop"

// =================================================================================================
// -------------------------------------------------------------------------------------------------
// this is a debug tool: the Ascii terminal program moves the cursor and screen when debug values are
// being displayed: if the complete recording of Ascii output up to now is interesting, stop Agency.
// App FSM (in this forced App) components all gate future activity on Agency running right now.
// -------------------------------------------------------------------------------------------------
int     iterations = 0;

// -------------------------------------------------------------------------------------------------
// An example of other parties gating activity based on the state of ssTEA Time and Agency, this
// interface into ssTEA allows the App's loop to remain intact when converting into a SimpleSal App.
// -------------------------------------------------------------------------------------------------
void    AppLoop_ssTEA_Interface (void)
{
    ssUI_db_pEvApi_t    pEvApi;
    boolean             bItIsTime_ToStopAgency;     // any path sets a valid value

#ifdef APP_OPTIN_ANNOUNCE_EVENT
    mesa_uiOp_emit_newline ();
    App_Announce_Event ("......" );
    App_Announce_Event ("App's loop detected a 1 second Time boundary 5 times, turned LED On.");
    ss_uiOp_Show_Time (ssT_gpTime_Current, lfY);
    App_Announce_Event ("App's loop interacts with ssTEA to schedule LED Off Time Event.");
#endif  // APP_OPTIN_ANNOUNCE_EVENT

    // ---------------------------------------------------------------------------------------------
    // What the "app-events.ino" does: WHEN the LED is turned On (here), a Time period starts
    // during which the LED will be On.  When that period ends, the LED will be turned off.
    // The Time at which the Event is based on software setting OccursAt to "Current + period"
    // AND signaling the Time Event to resume; this causes the Time Event to participate.
    // When the Time Event is granted Agency, it will set the LED to Off and then pause again.
    // ---------------------------------------------------------------------------------------------
    // When the ssUI variable ssUI_gpTimeA has a value of zero, Time Event occurs immediately.
    // When the variable is non-zero, the Time Event occurs at the end of a Duty Cycle Period.
    // ---------------------------------------------------------------------------------------------
    pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (TIMEevent_EVENT_API);
    debug_Show_OneEvApi (pEvApi);

    // F14M36: the (forced) Time Event is granted Agency based on the current OccursAt set by App
    ssT_mathOp_P1getsP2 (&pEvApi->pssTEA_ApiSig->ssE_pAboutEv->OccursAt, ssT_gpTime_Current);
    ssT_mathOp_P1getsP1plusP2 (&pEvApi->pssTEA_ApiSig->ssE_pAboutEv->OccursAt, App_Duty_OnTime);

#ifdef APP_OPTIN_ANNOUNCE_EVENT
    App_Announce_Event ("Off Event scheduled @");
    ss_uiOp_Show_Time (&pEvApi->pssTEA_ApiSig->ssE_pAboutEv->OccursAt, lfY);
#endif  // APP_OPTIN_ANNOUNCE_EVENT

    // assert: there is no path through this switch that does not set bItIsTime_ToStopAgency
    switch (pEvApi->pssTEA_ApiSig->ssE_pAboutEv->Runfsm_state)
    {
        case ssA_Runfsm_State_stopped   :
            bItIsTime_ToStopAgency = true;
            App_Announce_Event ("found Stopped Time Event, an error.");
            break;
        case ssA_Runfsm_State_paused    :
            if (!ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgRunfsm_Resume))
            {
                bItIsTime_ToStopAgency = true;
                App_Announce_Event ("Paused Time Event did not Resume, an error.");
            }
            else
            {
                bItIsTime_ToStopAgency = false;
                App_Announce_Event ("Paused Time Event resumed, not an error.");
            }
            break;
        case ssA_Runfsm_State_agencying :
            bItIsTime_ToStopAgency = false;
            App_Announce_Event ("Agencying Time Event is not paused, not an error.");
            break;
        case ssA_Runfsm_State_flaw      :
            bItIsTime_ToStopAgency = true;
            App_Announce_Event ("Agencying Time Event state is flawed, an error.");
            break;
        default :
            bItIsTime_ToStopAgency = true;
            App_Announce_Event ("Agencying Time Event state is invalid, an error.");
            break;
    }   // switch on RunFSM state

    // ---------------------------------------------------------------------------------------------
    // Simply turn off any agency granting that results in debug or normal output to review output;
    // or, simply turn agencying on and off periodically to control when ssTEA co-exists with App.
    // ---------------------------------------------------------------------------------------------
    if (iterations > 0)
    {
        --iterations;
        if (iterations == 0)            // only the transition from nonzero to zero stops agency
        {
            bItIsTime_ToStopAgency = true;
        }
    }

    if (bItIsTime_ToStopAgency)
    {
        ssTEA_control.Agency_state = ssTEA_state_stopped;
    }
}   // AppLoop_ssTEA_Interface
// =================================================================================================
// Events: definition, launch into participation in ssTEA Agency FSMs, actions taken given agency.
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// This encapsulates the definition and launching within ssTEA of the Time Event and the Data Event.
// -------------------------------------------------------------------------------------------------
ssE_EvResult_t App_EventLauncher (void)
{
    ssUI_db_pEvApi_t    TimeEvent_pEvApi;
    ssUI_db_pEvApi_t    DataEvent_pEvApi;
    ssUI_db_pEvApi_t    StatsEvent_pEvApi;

    ssE_EvResult_t      EvResult;

    App_Announce_App ("- App Launcher of Events: [Time, Data, Stats]");

    TimeEvent_pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (TIMEevent_EVENT_API);
    debug_Show_OneEvApi (TimeEvent_pEvApi);
    DataEvent_pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (DATAevent_EVENT_API);
    debug_Show_OneEvApi (DataEvent_p );
    StatsEvent_pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (STATSevent_EVENT_API);
    debug_Show_OneEvApi (StatsEvent_pEvApi);

    App_Announce_App ("  ");        // space a line
    App_Announce_App ("-- Time event launch: define");

    EvResult = App_TimeEvent_Define (TimeEvent_pEvApi);
    debug_Show_OneEvApi (TimeEvent_pEvApi);
    if (EvResult != ssE_EvResult_OK_go)
    {
        App_Announce_Event ("Time Event definition error");
        App_Announce_App (pcMsg_AppLauncherFailed);
        return (EvResult);
    }

    App_Announce_App ("  ");        // space a line
    App_Announce_App ("-- Data event launch: define");

    EvResult = App_DataEvent_Define (DataEvent_pEvApi);
    debug_Show_OneEvApi (DataEvent_pEvApi);
    if (EvResult != ssE_EvResult_OK_go)
    {
        App_Announce_Event ("Data Event definition error");
        App_Announce_App (pcMsg_AppLauncherFailed);
        return (EvResult);
    }

    App_Announce_App ("  ");        // space a line
    App_Announce_App ("-- Stats event launch: define");

    EvResult = App_StatsEvent_Define (StatsEvent_pEvApi);
    debug_Show_OneEvApi (StatsEvent_pEvApi);
    if (EvResult != ssE_EvResult_OK_go)
    {
        App_Announce_Event ("Stats Event definition error");
        App_Announce_App (pcMsg_AppLauncherFailed);
        return (EvResult);
    }

    App_Announce_App ("  ");        // space a line
    App_Announce_App ("-- Time event launch: operate");

    EvResult = App_TimeEvent_Launch (TimeEvent_pEvApi);
    debug_Show_OneEvApi (TimeEvent_pEvApi);
    if (EvResult != ssE_EvResult_OK_go)
    {
        App_Announce_Event ("Time Event Launch attempt failed");
        App_Announce_App (pcMsg_AppLauncherFailed);
        return (EvResult);
    }
    App_Announce_App ("-- Time Event Launched");

    App_Announce_App ("  ");        // space a line
    App_Announce_App ("-- Data event launch: operate");

    EvResult = App_DataEvent_Launch (DataEvent_pEvApi);
    debug_Show_OneEvApi (DataEvent_pEvApi);
    if (EvResult != ssE_EvResult_OK_go)
    {
        App_Announce_Event ("Data Event Launch attempt failed");
        App_Announce_App (pcMsg_AppLauncherFailed);
        return (EvResult);
    }
    App_Announce_App ("-- Data Event Launched");

    App_Announce_App ("  ");        // space a line
    App_Announce_App ("-- Stats event launch: operate");

    EvResult = App_StatsEvent_Launch (StatsEvent_pEvApi);

    debug_Show_OneEvApi (StatsEvent_pEvApi);
    if (EvResult != ssE_EvResult_OK_go)
    {
        App_Announce_Event ("Stats Launch attempt failed");
        App_Announce_App (pcMsg_AppLauncherFailed);
        return (EvResult);
    }
    App_Announce_App ("-- Stats Event Launched");

    App_Announce_App ("  ");        // space a line
    App_Announce_App ("- [Time, Data, Stats] Event Launch attempts complete");

    return (EvResult);
}   // App_EventLauncher
// =================================================================================================
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// This defines an Event FSM in the language ssTEA uses to manage an Event within an operating FSM.
// -------------------------------------------------------------------------------------------------
ReadOnly pAsciiA_t  pcTimeEvent             = S("TimeEvent");
ssUI_Token_t        myTimeEventTkn          = { pcTimeEvent     , 9, NoBananas };

ssE_EvResult_t App_TimeEvent_Define (ssUI_db_pEvApi_t pEvApi)
{
    ssTEA_pApiSig_t         pApiSig;                // create local expressions for an object within
    ssE_pAboutEv_t          ssE_pAboutEv;           //   the EvApi data pointed to by the caller

    // ---------------------------------------------------------------------------------------------
    // The data structure ssTEA uses to hold information "About the Event" does not exist yet; when
    // the Api FSM is On it does exist.  The "EvApi" data is ssUI's free built-in allocation of the
    // medium or signal carrier used to communicate with ssTEA: memory the processor can access.
    // The token defined here is used by ssTEA and ssUI to describe whose EvApi the data belongs to.
    // ---------------------------------------------------------------------------------------------
    pEvApi->pEvApiNameTkn_App = &myTimeEventTkn;

    App_Announce_App (pcMsg_AgApifsm_OnReq);
    if (!ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgApifsm_On))
    {
        App_Announce_ssTEA ("Request to set Time Event Agency API FSM state to On failed, an error.");
        return (ssE_EvResult_notOK_state);
    }

    // ---------------------------------------------------------------------------------------------
    // The signal carrier for the Event API to ssTEA has a pointer to the ssTEA data About the Event.
    // Change focus to ssTEA's view of or about the event. Where the data is should not matter now.
    // ---------------------------------------------------------------------------------------------
    // NOTE: This complex ssTEA detail matters only when changing from one style to the other.  Later.
    // ---------------------------------------------------------------------------------------------
    // NOTE: This is a result of the design of ssUI supporting N Events inherently for the App's use.
    // NOTE: ssUI provides an array of data structures, the App may alternatively use N variables.
    // The point here is the App must have data it knows about any medium within the App's context.
    // ---------------------------------------------------------------------------------------------
    pApiSig = pEvApi->pssTEA_ApiSig;
    ssE_pAboutEv = pApiSig->ssE_pAboutEv;

    // ---------------------------------------------------------------------------------------------
    // The App loop (in this forced example) turns On the LED every N seconds (example: 5 seconds).
    // With the LED On, the App loop changes the OccursAt Time and period and resumes the Time Event.
    // ---------------------------------------------------------------------------------------------
    // The Time Event turns Off the LED when the period of Time completes (example: 3 seconds).
    // The Time Event, while agencying, waits to be granted Agency.  The period between App loop's
    // LED On and Event's LED Off is the period of Time "On Duty"; as a percentage, "Duty Cycle".
    // ---------------------------------------------------------------------------------------------
    // Why? An off|on|off cycle repeating has a period On and a period Off; an oscillating signal
    // has a Duty Cycle of 50%.  Power management in SOC chips is based on reducing the Duty cycle
    // (as % of a power signal cycle) down to ONLY that needed, by controlling the power duty cycle.
    // This is not changing the rate the signal goes off|on|off, but how long the on period is.
    // ---------------------------------------------------------------------------------------------
    // This is where the concept of pointers to code is used: assign an address to a variable.
    // ---------------------------------------------------------------------------------------------
    // F14B16: Time Event (and others) fails in validation of event definition
    ssE_pAboutEv->pEvFunc = &App_TimeEvent_Operate;

    ssE_pAboutEv->Runfsm_EvType = ssE_EvType_Time;
    ssT_mathOp_P1getsP2 (&ssE_pAboutEv->OccursAt, ssT_gpTime_Current);
    ssT_mathOp_P1getsP1plusP2 (&pEvApi->pssTEA_ApiSig->ssE_pAboutEv->OccursAt, App_StartTimeFromNow);

    // F14M36: the (forced) Time Event is granted Agency based on the current OccursAt set by App
    // F13M36: the (canonical) Time Event completes; ssTEA calculates OccursAt = Current + Period
    // F14M36:     ssE_pAboutEv->recurs = true;
    // F14M36:     ssE_pAboutEv->recursFromTrue = true;
    // F14M36:     ssT_mathOp_P1getsP2 (&ssE_pAboutEv->Period, App_Duty_OnTime);

    ssE_pAboutEv->recurs = false;
    ssE_pAboutEv->recursFromTrue = true;

    ssE_pAboutEv->App_pEventData = (EvEx_App_pEventData_t) &pEvApi->App_EventData;

    App_Announce_App ("Time Event Agency API On; Time Event Defined");

    return (ssE_EvResult_OK_go);
}  // App_TimeEvent_Define
// -------------------------------------------------------------------------------------------------
// This will "launch the App Event into ssTEA's FSM control", using a definition created by the App.
// -------------------------------------------------------------------------------------------------
ssE_EvResult_t App_TimeEvent_Launch (ssUI_db_pEvApi_t pEvApi)
{
    // vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    actual launch of the Event in ssTEA
    ssE_EvResult_t  EvResult = App_Launch_in_ssTEA (pEvApi);

#ifdef APP_ONEOF_TIME_START_ZERO
    // F14B17: when configured as from The BigBang, start Time from Now is rejected (probably zero).
#endif // APP_ONEOF_TIME_START_ZERO

    // ---------------------------------------------------------------------------------------------
    // A Launched Time Event is by definition in the Agencying state.  The NEXT moment in Time the
    // Launched Time Event COULD be granted Agency by ssTEA is the NEXT moment in Time Agency is
    // granted to ssTEA by the App's loop, the Event will be considered and granted Agency by ssTEA.
    // ---------------------------------------------------------------------------------------------
    // For the purposes of this (forced) example, and to make the reader think about Time, a flawed
    // Time Event model is forced.  Normal use of Time Events is to OccurAt one or both transitions;
    // the Period for these transitions remains constant so the Event simply recurs in ssTEA's view.
    // Also forced is the Event's request on exit to be returned to the Paused state from Agencying.
    // ---------------------------------------------------------------------------------------------
    // Normal use of a recurring Time Event is to cause on/off signal transitions at a frequency and
    // the duty cycle is 50%: half of the period of Time on, then half of the period of Time off.
    // ---------------------------------------------------------------------------------------------
    if (EvResult == ssE_EvResult_OK_go)
    {
        // F14M36: the (forced) Time Event is granted Agency based on the current OccursAt set by App
        if (ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgRunfsm_Pause))
        {
            App_Announce_App ("Agencying Time Event paused");
        }   // Pause succeeded
        else
        {   // Pause failed
            App_Announce_ssTEA ("Error: Agency Api FSM failed to pause while Agencying");
            EvResult = ssE_EvResult_notOK_API;
        }   // Pause failed
    }   // Launch in ssTEA succeeded
    else
    {   // Launch in ssTEA failed
        App_Announce_App ("Error: Agency Api FSM Launch failed");
    }   // Launch in ssTEA failed

    return (EvResult);
}  // App_TimeEvent_Launch
// -------------------------------------------------------------------------------------------------
// The content here that is ssTEA-related software: 1) makes sure not init state; 2) return Pause.
// The content that is App-related software: 1) signal Data Event with data; turn the LED off.
// -------------------------------------------------------------------------------------------------
// Note that this Event does not refer to About Event data of its own, but that of the Data Event.
// -------------------------------------------------------------------------------------------------
Ascii_t     MsgIndex = 'A';

ssE_EvResult_t App_TimeEvent_Operate (ssE_pAboutEvVoid_t param1, ssT_pTime_t pCurrentTime)
{
    ssUI_db_pEvApi_t    DataEvent_pEvApi;

    if (param1 == pVoidEvParam1Null)
    {
        App_Announce_Event ("App_TimeEvent_Operate in init state...");
        return (ssE_EvResult_OK_go);
    }

    mesa_uiOp_LEDoff ();

#ifdef APP_OPTIN_ANNOUNCE_APP
    ss_uiOp_Show_Time (ssT_gpTime_Current, lfY);
    App_Announce_App ("App_TimeEvent_Operate in agencying state turned LED off...");
    App_Announce_App ("App_TimeEvent_Operate in agencying state sending msg to Data Event...");
#endif  // APP_OPTIN_ANNOUNCE_APP

    // ---------------------------------------------------------------------------------------------
    // One method for communicating between the App's context and the Event's context is to simply
    // refer to variables within the scope or view of the software: global to the App and the Event.
    // ---------------------------------------------------------------------------------------------
    // For the array, the global variable is the space allocated for this Event by the App in EvApi.
    // For the index, the global variable is the space allocated by a variable outside any function.
    // ---------------------------------------------------------------------------------------------
    DataEvent_pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (DATAevent_EVENT_API);

    if (++MsgIndex > 'Z') MsgIndex = 'A';
    DataEvent_pEvApi->App_EventData.Data[0] = Ascii_squiggleLBracket;
    DataEvent_pEvApi->App_EventData.Data[1] = MsgIndex;
    DataEvent_pEvApi->App_EventData.Data[2] = Ascii_squiggleRBracket;
    DataEvent_pEvApi->App_EventData.Data[3] = Ascii_Space;

    (void) ssUI_AaOp_pP1_gets_pP2max (&DataEvent_pEvApi->App_EventData.Data[4],
                   S("msg from Time Event: LED turned off   "), (APP_DATA_MAX_I-4));

    // ---------------------------------------------------------------------------------------------
    // The Time Event sends a signal to ssTEA to resume the Data Event, using the Data Event's API.
    // ---------------------------------------------------------------------------------------------
    if (!ssUI_apiSignalOp_Emit (DataEvent_pEvApi, ss_ApiSigMsgValue_AgRunfsm_Resume))
    {
        App_Announce_ssTEA ("attempt to signal Data Event resume by LED Off failed");
        return (ssE_EvResult_notOK_state);
    }

    // F14M36: the (forced) Time Event is granted Agency based on the current OccursAt set by App
    return (ssE_EvResult_OK_pauseMe);
}   // App_TimeEvent_Operate
// =================================================================================================
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------------
ReadOnly pAsciiA_t  pcDataEvent             = S("DataEvent");
ssUI_Token_t        myDataEventTkn          = { pcDataEvent     , 9, NoBananas };

ssE_EvResult_t App_DataEvent_Define (ssUI_db_pEvApi_t pEvApi)
{
    ssTEA_pApiSig_t         pApiSig;                // create a local expression for an object within
    ssE_pAboutEv_t          ssE_pAboutEv;           // same

    pEvApi->pEvApiNameTkn_App = &myDataEventTkn;

    App_Announce_App (pcMsg_AgApifsm_OnReq);
    if (!ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgApifsm_On))
    {
        App_Announce_ssTEA ("Request to set Data Event Agency API FSM state to On failed, an error.");
        return (ssE_EvResult_notOK_state);
    }

    pApiSig = pEvApi->pssTEA_ApiSig;
    ssE_pAboutEv = pApiSig->ssE_pAboutEv;

    // ---------------------------------------------------------------------------------------------
    // Everything about a Data Event's data is defined by the Data Event: format, location, alloc.
    // ---------------------------------------------------------------------------------------------
    // This is where the concept of pointers to code is used: assign an address to a variable.
    // ---------------------------------------------------------------------------------------------
    // F14B16: Time Event (and others) fails in validation of event definition
    ssE_pAboutEv->pEvFunc = &App_DataEvent_Operate;
    ssE_pAboutEv->Runfsm_EvType = ssE_EvType_Data;
    ssE_pAboutEv->App_pEventData = (EvEx_App_pEventData_t) &pEvApi->App_EventData;

    App_Announce_App ("Data Event Agency API On; Data Event Defined");
    return (ssE_EvResult_OK_go);
}  // App_DataEvent_Define
// -------------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------------
ssE_EvResult_t App_DataEvent_Launch (ssUI_db_pEvApi_t pEvApi)
{
    // vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    actual launch of the Event in ssTEA
    ssE_EvResult_t  EvResult = App_Launch_in_ssTEA (pEvApi);

    if (EvResult == ssE_EvResult_OK_go)
    {
        // F14B48: a Data Event launched successfully is put into Paused state by ssA
        if (ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgRunfsm_Pause))
        {
            App_Announce_App ("Agencying Data Event paused");
        }   // Pause succeeded
        else
        {   // Pause failed
            App_Announce_ssTEA ("Error: Data Event Agency Run FSM failed to pause while Agencying");
            EvResult = ssE_EvResult_notOK_API;
        }   // Pause failed
    }   // launched now agencying

    return (EvResult);
}  // App_DataEvent_Launch
// -------------------------------------------------------------------------------------------------
// The content here that is ssTEA-related software: 1) makes sure not init state; 2) return Pause.
// The content that is App-related software: 1) emit the bytes given to the output device.
// -------------------------------------------------------------------------------------------------
ssE_EvResult_t App_DataEvent_Operate (ssE_pAboutEvVoid_t param1, ssT_pTime_t pCurrentTime)
{
#ifdef APP_OPTIN_ANNOUNCE_EVENT
    ssE_pAboutEv_t      ssE_pAboutEv;      // valid after param1 is qualified as non-NULL
    App_pEventData_t    local_App_pEventData;
#endif  // APP_OPTIN_ANNOUNCE_EVENT

    if (param1 == pVoidEvParam1Null)
    {
        App_Announce_Event ("App_DataEvent_Operate in init state...");
        return (ssE_EvResult_OK_go);
    }

    App_Announce_Event ("App_DataEvent_Operate in agencying state emits Time Event data...");

    // ---------------------------------------------------------------------------------------------
    // One method for communicating between the App's context and the Event's context is an array
    // with the App's data tucked into the About Event data given to the Event when Agency granted.
    // ---------------------------------------------------------------------------------------------
#ifdef APP_OPTIN_ANNOUNCE_EVENT
    ssE_pAboutEv = (ssE_pAboutEv_t) param1;
    local_App_pEventData = (App_pEventData_t) ssE_pAboutEv->App_pEventData;
    App_Announce_Event (&local_App_pEventData->Data);
    ss_uiOp_Show_Time (ssT_gpTime_Current, lfY);
#endif  // APP_OPTIN_ANNOUNCE_EVENT

    // a Data Event returning OK is paused by ssA
    return (ssE_EvResult_OK_go);
}   // App_DataEvent_Operate
// =================================================================================================
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// The Statistics Event recurs periodically to create a Time basis for a legacy Timekeeping model.
// When the Event operates, it KNOWS a period of Time has occured, because Agency has been granted.
// -------------------------------------------------------------------------------------------------
// The Statistics Event:
//
//  1) Calculates the value using current information "about the Event": the number of times Agency
//      was granted by ssTEA, changes from Paused to Agencying, changes from Agencying to Paused.
//  2) The difference between these values and the values saved from the last Time the Event did
//      the calculations shows the number of Agency changes by the Event within a Period of Time.
// -------------------------------------------------------------------------------------------------
ReadOnly pAsciiA_t  pcStatsEvent             = S("StatsEvent");
ssUI_Token_t        myStatsEventTkn          = { pcStatsEvent     , 9, NoBananas };

// #define APP_ONEOF_SHOW_STATS
// #define APP_ONEOF_PLOT_STATS

// The define for the debug is never enabled unless the SHOW_STATS define occurs first
#ifdef APP_ONEOF_SHOW_STATS
// #define DEBUG_STATSEVENT_TIME
#endif  // APP_ONEOF_SHOW_STATS

// -------------------------------------------------------------------------------------------------
// Statistics proliferate and propagate and regenerate.  Easier: have generic variables always
// allocated here and named here, and then, when a statistic becomes interesting, #define a usage.
// -------------------------------------------------------------------------------------------------
int         Stats_int_1;
int         Stats_int_2;
int         Stats_int_3;
int         Stats_int_4;

ssE_EvResult_t App_StatsEvent_Define (ssUI_db_pEvApi_t pEvApi)
{
    ssTEA_pApiSig_t         pApiSig;
    ssE_pAboutEv_t          ssE_pAboutEv;
    ssUI_db_pEvApi_t        TimeEvent_pEvApi;

    pEvApi->pEvApiNameTkn_App = &myStatsEventTkn;

    App_Announce_App (pcMsg_AgApifsm_OnReq);
    if (!ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgApifsm_On))
    {
        App_Announce_ssTEA ("Request to set Stats Event Agency API FSM state to On failed, an error.");
        return (ssE_EvResult_notOK_state);
    }

    pApiSig = pEvApi->pssTEA_ApiSig;
    ssE_pAboutEv = pApiSig->ssE_pAboutEv;

    ssE_pAboutEv->pEvFunc = &App_StatsEvent_Operate;
    ssE_pAboutEv->Runfsm_EvType = ssE_EvType_Time;

    // use the OccursAt start Time value set by the Time Event (for itself) for Stats start Time
    TimeEvent_pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (TIMEevent_EVENT_API);
    ssT_mathOp_P1getsP2 (&ssE_pAboutEv->OccursAt,
                         &TimeEvent_pEvApi->pssTEA_ApiSig->ssE_pAboutEv->OccursAt);

    ssE_pAboutEv->recurs = true;
    ssE_pAboutEv->recursFromTrue = true;
    ssT_mathOp_P1getsP2 (&ssE_pAboutEv->Period, App_pStats_Period_Emit);

#ifdef DEBUG_STATSEVENT_TIME
    ssUI_dbOp_Show_OneEvApi (pEvApi);                                   // F14B17 debug
#endif // DEBUG_STATSEVENT_TIME

    ssE_pAboutEv->App_pEventData = (EvEx_App_pEventData_t) &pEvApi->App_EventData;
    pEvApi->App_EventData.Stats_CalcPeriod_ms = App_CalcPeriod;
    pEvApi->App_EventData.Stats_CalcPeriod_ct = pEvApi->App_EventData.Stats_CalcPeriod_ms;
    pEvApi->App_EventData.Stats_EmitPeriod_ms = App_EmitPeriod;
    pEvApi->App_EventData.Stats_EmitPeriod_ct = pEvApi->App_EventData.Stats_EmitPeriod_ms;

    Stats_int_1 = Stats_int_2 = Stats_int_3 = Stats_int_4 = 0;

    App_Announce_App ("Stats Event Agency API On; Stats Event Defined");

    return (ssE_EvResult_OK_go);
}  // App_StatsEvent_Define
// -------------------------------------------------------------------------------------------------
// B17
// -------------------------------------------------------------------------------------------------
ssE_EvResult_t App_StatsEvent_Launch (ssUI_db_pEvApi_t pEvApi)
{
    // vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    actual launch of the Event in ssTEA
    ssE_EvResult_t  EvResult = App_Launch_in_ssTEA (pEvApi);

    if (EvResult != ssE_EvResult_OK_go)
    {   // Launch in ssTEA failed
        App_Announce_App ("Error: Agency Api FSM Launch failed");
        App_Announce_Event ("event launch failed in <App_Launch_in_ssTEA>");
    }   // Launch in ssTEA failed

#ifdef DEBUG_STATSEVENT_TIME
    ssUI_dbOp_Show_OneEvApi (pEvApi);                                   // F14B17 debug
#endif // DEBUG_STATSEVENT_TIME
    return (EvResult);
}  // App_StatsEvent_Launch
// -------------------------------------------------------------------------------------------------
// The Statistics Events FSM both calculates statistics and emits them to the plotter, periodically.
// The calculation occurs periodically; the current value is the result of the last calculation.
// The emission to the plotter occurs periodically; the value emitted is the current value.
// -------------------------------------------------------------------------------------------------
// WHEN statistics are emitted, EITHER a table of stats is displayed, or, signals are "plottered".
// The tables of numbers are useful when things are not working; the graphs show things are working.
// -------------------------------------------------------------------------------------------------
void    App_CalcStats (void);
void    App_EmitStats (void);

ssE_EvResult_t App_StatsEvent_Operate (ssE_pAboutEvVoid_t param1, ssT_pTime_t pCurrentTime)
{
#ifdef DEBUG_STATSEVENT_TIME
    // F14B24: debug output hard faults if assignment to the pEvApi is not made first (below)
    StatsEvent_pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (STATSevent_EVENT_API);
#endif // DEBUG_STATSEVENT_TIME

    boolean             CalcPeriod_Completed = false;
    boolean             EmitPeriod_Completed = false;

    ssUI_db_pEvApi_t    StatsEvent_pEvApi;
    ssE_EvResult_t      ReturnResult = ssE_EvResult_OK_go;

    if (param1 == pVoidEvParam1Null)
    {
        App_Announce_Event ("App_StatsEvent_Operate in init state...");
        return (ReturnResult);
    }

#ifdef APP_ONEOF_SHOW_STATS
#ifdef APP_OPTIN_ANNOUNCE_EVENT
    ss_uiOp_Show_Time (pCurrentTime, lfN);
    App_Announce_Event ("   App_StatsEvent_Operate in Agencying state...");
#endif  // APP_OPTIN_ANNOUNCE_EVENT
#endif  // APP_ONEOF_SHOW_STATS

    // ---------------------------------------------------------------------------------------------
    // This countdown algorithm creates a legacy Timekeeping model, based on this Event's period.
    // A countdown timer or a countup timer is an FSM with an Initial state of "# times to count 1"
    // (where 0 means "don't count"). The algorithm for each is specific; this is a countdown timer.
    // ---------------------------------------------------------------------------------------------
    // This countdown timer algorithm decrements what it knows to be a positive integer.  Countdown
    // algorithms may signal an FSM for action when the result of the decrement operation is zero.
    // The value of the countdown after the action is taken is also a function of the algorithm.
    // ---------------------------------------------------------------------------------------------
    StatsEvent_pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (STATSevent_EVENT_API);
    if (StatsEvent_pEvApi->App_EventData.Stats_CalcPeriod_ct > 0)
    {
        // when the signal changes from nonzero to zero, calculate the statistics
        --StatsEvent_pEvApi->App_EventData.Stats_CalcPeriod_ct;
        if (StatsEvent_pEvApi->App_EventData.Stats_CalcPeriod_ct == 0)
        {
            StatsEvent_pEvApi->App_EventData.Stats_CalcPeriod_ct =
                    StatsEvent_pEvApi->App_EventData.Stats_CalcPeriod_ms;
            CalcPeriod_Completed = true;
        }
    }   // not displaying stats using a countdown timer

    if (StatsEvent_pEvApi->App_EventData.Stats_EmitPeriod_ct > 0)
    {
        // when the signal changes from nonzero to zero, display the statistics
        --StatsEvent_pEvApi->App_EventData.Stats_EmitPeriod_ct;
        if (StatsEvent_pEvApi->App_EventData.Stats_EmitPeriod_ct == 0)
        {
            StatsEvent_pEvApi->App_EventData.Stats_EmitPeriod_ct =
                    StatsEvent_pEvApi->App_EventData.Stats_EmitPeriod_ms;
            EmitPeriod_Completed = true;
        }
    }   // not displaying stats using a countdown timer

    if (CalcPeriod_Completed)
    {
#ifdef APP_ONEOF_PLOT_STATS
        App_CalcStats ();
#endif  // APP_ONEOF_PLOT_STATS
    }   // time to send it

    if (EmitPeriod_Completed)
    {
#ifdef APP_ONEOF_SHOW_STATS
        // ----------------------------------------------------------------------------------------
        // Function called is what would be found and invoked by the menu FSM: "ss agency stats".
        // Actually skipped fake input and just lied to the function: 3 tokens matched by the FSM.
        // ----------------------------------------------------------------------------------------
        if (H_ss_AgencyStats (ssUI_tkn3rd_i, false) != eH_rHandled)
        {
            return (ssE_EvResult_OK_stopMe);
        }
#ifdef DEBUG_STATSEVENT_TIME
        // F14B24: debug output hard faults if assignment to the pEvApi is not made first
        ssUI_dbOp_Show_OneEvApi (StatsEvent_pEvApi);
#endif // DEBUG_STATSEVENT_TIME
#endif  // APP_ONEOF_SHOW_STATS

#ifdef APP_ONEOF_PLOT_STATS
        App_PlotStats ();
#endif  // APP_ONEOF_PLOT_STATS
    }   // time to send it

    return (ReturnResult);
}   // App_StatsEvent_Operate
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// Statistics proliferate and propagate and regenerate.  Easier: have generic variables always
// allocated here and named here, and then, when a statistic becomes interesting, #define a usage.
// -------------------------------------------------------------------------------------------------
#define last_AgencyingToPaused_ct   Stats_int_1
#define last_PausedToAgencying_ct   Stats_int_2
#define last_AgencyGranted_ct       Stats_int_3

ssA_All_Stats_t         AllEvs_All_Stats;
ssA_All_Stats_t         ThisEv_All_Stats;

// -------------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------------
void    App_CalcStats (void)
{
    ssUI_db_pEvApi_t        pEvApi;
    int                     EvApi_i;

    ssA_statOp_All_Zero (&AllEvs_All_Stats);

    for (EvApi_i = 0; EvApi_i <= SSUI_EVAPI_ALLOC_MAX_I; EvApi_i++)
    {
        pEvApi = ssUI_dbOp_Lookup_UsingEvApi_i (EvApi_i);
        if (!pEvApi->accessOn)
        {
            continue;
        }
        if (pEvApi->pssTEA_ApiSig->Apifsm_state == ssA_Apifsm_state_off)
        {
            continue;
        }
        if (EvApi_i == STATSevent_EVENT_API)            // only include Time and Data Events
        {
            continue;
        }

        ssA_statOp_All_Zero (&ThisEv_All_Stats);

        if (ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgApifsm_Stats))
        {
            if (pEvApi->pssTEA_ApiSig->pApiSigData != pApiSigDataNull)
            {
                ssA_statOp_Apifsm_P1getsP2
                    (
                        &ThisEv_All_Stats.Apifsm,
                        (ssA_pApifsm_Stats_t) pEvApi->pssTEA_ApiSig->pApiSigData
                    );
            }
        }   // Api signal for ApiFsm stats

        if (ssUI_apiSignalOp_Emit (pEvApi, ss_ApiSigMsgValue_AgRunfsm_Stats))
        {
            if (pEvApi->pssTEA_ApiSig->pApiSigData != pApiSigDataNull)
            {
                ssA_statOp_Runfsm_P1getsP2
                    (
                        &ThisEv_All_Stats.Runfsm,
                        (ssA_pRunfsm_Stats_t) pEvApi->pssTEA_ApiSig->pApiSigData
                    );
            }   // params pointer is non-NULL
        }   // if Runfsm stats signal worked

        ssA_statOp_Apifsm_P1getsP1plusP2 (&AllEvs_All_Stats.Apifsm, &ThisEv_All_Stats.Apifsm);
        ssA_statOp_Runfsm_P1getsP1plusP2 (&AllEvs_All_Stats.Runfsm, &ThisEv_All_Stats.Runfsm);
    }   // for
}   // App_CalcStats
// -------------------------------------------------------------------------------------------------
// At a Time in the Future, this function will become a general-purpose plotter output Time Event;
// abstracted down to "the last value for this", "the current value for this", and "name of this".
// -------------------------------------------------------------------------------------------------
int     last_GNT    = 0;
int     last_P2A    = 0;
int     last_A2P    = 0;

void    App_PlotStats (void)
{
    static  int     PlotClock = 0;
    pAscii_t        pClockValue;
    int             temp;

    temp = AllEvs_All_Stats.Runfsm.EvEx.AgencyGranted_ct - last_GNT;
    mesa_uiOp_emit_qAsciiA ("GNT:");
    mesa_uiOp_emit_Int_999 (temp);
    mesa_uiOp_emit_newline ();
    last_GNT = AllEvs_All_Stats.Runfsm.EvEx.AgencyGranted_ct;

    temp =  AllEvs_All_Stats.Runfsm.App.PausedToAgencying_ct - last_P2A;
    mesa_uiOp_emit_qAsciiA ("P2A:");
    mesa_uiOp_emit_Int_999 (temp);
    mesa_uiOp_emit_newline ();
    last_P2A = AllEvs_All_Stats.Runfsm.App.PausedToAgencying_ct;

    temp =  AllEvs_All_Stats.Runfsm.App.AgencyingToPaused_ct - last_A2P;
    mesa_uiOp_emit_qAsciiA ("A2P:");
    mesa_uiOp_emit_Int_999 (temp);
    mesa_uiOp_emit_newline ();
    last_A2P = AllEvs_All_Stats.Runfsm.App.AgencyingToPaused_ct;

    mesa_uiOp_emit_qAsciiA ("CLK:");
    PlotClock   = (PlotClock == 0) ? 1 : 0;
    pClockValue = (PlotClock == 0) ? S("-1") : S("0");
    mesa_uiOp_emit_pAsciiA (pClockValue);
    mesa_uiOp_emit_newline ();

}   // App_PlotStats
// =================================================================================================
// -------------------------------------------------------------------------------------------------
// This function must be instantiated by the App in order to satisfy ssUI's reference when the
// App is built, but the function does not have to do anything with the user input provided.
// The app-events SimpleSal App does not accept or handle serial input, except to complain about it.
// -------------------------------------------------------------------------------------------------
void App_HeyProcessThis (pAsciiA_t  pReceivedInput)
{
    mesa_uiOp_emit_newline ();
    ss_uiOp_emit_lbld_AsciiA (S("App's command input processor called with:"), pReceivedInput);
    mesa_uiOp_emit_newline ();
} // App_HeyProcessThis

// end of file: app_events.ino


